# Naunet config document

[general]
creation_time = "10/03/2023 22:52:35"
name = "naunet_klu_cloud_custom"
description = "Example: chemical network from uclchem v1.3"
loads = []

[chemistry]
elements = ["E", "H", "D", "HE", "C", "N", "O", "MG", "SI", "S", "CL"]
pseudo_elements = ["CR", "CRP", "PHOTON", "CRPHOT"]
species = ["#C2", "#C2H", "#C2H2", "#C2H3", "#C2H4", "#C2H5", "#C2H5OH", "#C3H2", "#C4H", "#C4N", "#CH2CO", "#CH3CCH", "#CH3CN", "#CH3CNH", "#CH3OH", "#CH4", "#CO", "#CO2", "#CS", "#H2CN", "#H2CO", "#H2CS", "#H2O", "#H2S", "#H2S2", "#H2SIO", "#HC3N", "#HCL", "#HCN", "#HCOOCH3", "#HNC", "#HNCO", "#HNO", "#MG", "#N2", "#NCCN", "#NH3", "#NO", "#NO2", "#NS", "#O2", "#O2H", "#OCS", "#SIC", "#SIC2", "#SIC3", "#SIH4", "#SIO", "#SIS", "#SO", "#SO2", "C", "C+", "C2", "C2+", "C2H", "C2H+", "C2H2", "C2H2+", "C2H3", "C2H4", "C2H5", "C2H5OH", "C2H5OH2+", "C2N", "C2N+", "C2N2+", "C2NH+", "C3+", "C3H2", "C3H5+", "C3N", "C4H", "C4N", "C4N+", "CH", "CH+", "CH2", "CH2+", "CH2CO", "CH3", "CH3+", "CH3CCH", "CH3CN", "CH3CNH", "CH3CNH+", "CH3OH", "CH3OH2+", "CH4", "CH4+", "CH5+", "CL", "CL+", "CN", "CN+", "CO", "CO+", "CO2", "CS", "CS+", "E-", "H", "H+", "H2", "H2+", "H2CL+", "H2CN", "H2CO", "H2CO+", "H2CS", "H2CS+", "H2NO+", "H2O", "H2O+", "H2S", "H2S+", "H2S2", "H2S2+", "H2SIO", "H3+", "H3CO+", "H3CS+", "H3O+", "H3S+", "H5C2O2+", "HC3N", "HCL", "HCL+", "HCN", "HCN+", "HCNH+", "HCO", "HCO+", "HCO2+", "HCOOCH3", "HCS", "HCS+", "HE", "HE+", "HEH+", "HNC", "HNCO", "HNO", "HNO+", "HNS+", "HOC+", "HOCS+", "HS", "HS+", "HS2", "HS2+", "HSIS+", "HSO+", "HSO2+", "MG", "MG+", "N", "N+", "N2", "N2+", "N2H+", "NCCN", "NH", "NH+", "NH2", "NH2+", "NH3", "NH3+", "NH4+", "NO", "NO+", "NO2", "NS", "NS+", "O", "O+", "O2", "O2+", "O2H", "O2H+", "OCN", "OCS", "OCS+", "OH", "OH+", "S", "S+", "S2", "S2+", "SI", "SI+", "SIC", "SIC+", "SIC2", "SIC2+", "SIC3", "SIC3+", "SIH", "SIH+", "SIH2", "SIH2+", "SIH3", "SIH3+", "SIH4", "SIH4+", "SIH5+", "SIO", "SIO+", "SIOH+", "SIS", "SIS+", "SO", "SO+", "SO2", "SO2+"]
extra_species = []
network = ["reactions.ucl"]
format = ["uclchem"]
heating = []
cooling = []

[chemistry.grain]
model = "rr07x"

[chemistry.binding_energy]
"#CH4" = 960.0
"#NH3" = 5500.0
"#H2O" = 5600.0
"#C2" = 10000.0
"#MG" = 5300.0
"#C2H" = 3000.0
"#C2H2" = 2587.0
"#HCN" = 3700.0
"#HNC" = 3800.0
"#C2H3" = 2800.0
"#CO" = 1300.0
"#N2" = 1100.0
"#C2H4" = 2500.0
"#H2CN" = 2400.0
"#C2H5" = 3100.0
"#NO" = 1600.0
"#H2CO" = 4500.0
"#HNO" = 3000.0
"#O2" = 1200.0
"#CH3OH" = 5000.0
"#SIH4" = 13000.0
"#O2H" = 5000.0
"#H2S" = 2700.0
"#HCL" = 5172.0
"#C3H2" = 5900.0
"#CH3CCH" = 3000.0
"#SIC" = 3500.0
"#CH3CN" = 4680.0
"#CH2CO" = 2800.0
"#CH3CNH" = 3740.0
"#HNCO" = 4400.0
"#SIO" = 3500.0
"#CS" = 3200.0
"#CO2" = 2600.0
"#C2H5OH" = 5400.0
"#H2CS" = 4400.0
"#NO2" = 2400.0
"#NS" = 1900.0
"#H2SIO" = 4400.0
"#SO" = 2800.0
"#C4H" = 3737.0
"#HC3N" = 4580.0
"#NCCN" = 3000.0
"#SIC2" = 4300.0
"#HCOOCH3" = 4210.0
"#SIS" = 3800.0
"#OCS" = 2400.0
"#C4N" = 4000.0
"#SIC3" = 5100.0
"#SO2" = 3400.0
"#H2S2" = 3100.0

[chemistry.photon_yield]

[chemistry.shielding]
CO = "VB88Table"

[chemistry.rate_modifier]

[chemistry.ode_modifier]
[chemistry.ode_modifier.H2]
factors = ["H2formation", "-H2dissociation"]
reactants = [["H"], ["H2"]]

[chemistry.ode_modifier.H]
factors = ["-2.0 * H2formation", "2.0 * H2dissociation"]
reactants = [["H"], ["H2"]]

[ODEsolver]
solver = "cvode"
device = "cpu"
method = "sparse"

[summary]
num_of_elements = 9
num_of_species = 215
num_of_grains = 1
num_of_gas_species = 164
num_of_ice_species = 51
num_of_grain_species = 0
num_of_reactions = 2507
list_of_elements = ["CL", "MG", "SI", "S", "N", "HE", "O", "C", "H"]
list_of_species = ["#C2H3", "#C2H4", "#C2H5", "#C3H2", "#C4H", "#CH2CO", "#CH3CN", "#CS", "#H2CN", "#HNC", "#NO2", "#SIO", "CH3CNH", "#C2H", "#C2H2", "#C4N", "#CO", "#HC3N", "#HNCO", "#MG", "#NCCN", "#NO", "#O2", "#O2H", "#SIC", "#SIC2", "#SIC3", "#C2H5OH", "#CH3CCH", "#CO2", "#HCOOCH3", "#C2", "#H2SIO", "#HNO", "#N2", "#NS", "#OCS", "#SIS", "#SO", "#SO2", "#CH3CNH", "#CH3OH", "#H2CO", "#H2S2", "#HCL", "#HCN", "#H2CS", "#H2O", "#H2S", "C4N", "C3H2", "H2S2", "#NH3", "H2NO+", "H2SIO", "HCL+", "HEH+", "HNCO", "HNS+", "HOC+", "HSO+", "SIC3+", "#CH4", "#SIH4", "C4H", "CL", "CL+", "H2CN", "C2N2+", "C4N+", "SIH5+", "H2CL+", "H5C2O2+", "SIC3", "SIH4+", "C2H5OH2+", "C2NH+", "C3H5+", "CH2CO", "HSO2+", "C3N", "HCOOCH3", "SIC2+", "C3+", "H2S2+", "HCL", "HOCS+", "HS2", "NS+", "CH3CCH", "H3CS+", "SIC2", "SO2+", "H2CS", "H2CS+", "HC3N", "HSIS+", "SIS+", "HS2+", "O2H", "CH3CNH+", "NO2", "S2+", "C2H5", "C2H5OH", "SIC+", "C2N", "NCCN", "SIC", "HCS", "SIH2", "SIH3+", "SIS", "CH3OH2+", "OCN", "S2", "SIH3", "CH3CN", "NS", "OCS+", "SIH2+", "SO2", "HNO", "SIH", "SIO+", "SIOH+", "SIH+", "SIH4", "C2H3", "C2N+", "HCO2+", "CS+", "HCS+", "SIO", "CH3OH", "H3S+", "SO", "C2H4", "CH4+", "CS", "MG", "MG+", "SO+", "C2+", "O2H+", "CN+", "N2H+", "OCS", "H2S+", "HNO+", "CH5+", "N2+", "HS", "HCNH+", "H2+", "H3CO+", "SI", "C2H2", "HCN+", "HNC", "SI+", "CO+", "HS+", "CO2", "NH+", "NH2", "O2+", "N+", "NH2+", "C2H+", "NH4+", "C2H", "O+", "NO+", "H2CO+", "CH2+", "NH3+", "H2S", "H2O+", "OH+", "CH3+", "N2", "C2H2+", "C2", "CH2", "CH3", "CH+", "NH", "S+", "CN", "H2CO", "CH4", "HCO", "HCN", "NO", "CH", "NH3", "H3O+", "O2", "C+", "S", "OH", "N", "HE+", "HE", "H3+", "H+", "O", "C", "HCO+", "H2O", "CO", "H2", "E-", "H"]
list_of_species_alias = ["GC2H3I", "GC2H4I", "GC2H5I", "GC3H2I", "GC4HI", "GCH2COI", "GCH3CNI", "GCSI", "GH2CNI", "GHNCI", "GNO2I", "GSiOI", "CH3CNHI", "GC2HI", "GC2H2I", "GC4NI", "GCOI", "GHC3NI", "GHNCOI", "GMgI", "GNCCNI", "GNOI", "GO2I", "GO2HI", "GSiCI", "GSiC2I", "GSiC3I", "GC2H5OHI", "GCH3CCHI", "GCO2I", "GHCOOCH3I", "GC2I", "GH2SiOI", "GHNOI", "GN2I", "GNSI", "GOCSI", "GSiSI", "GSOI", "GSO2I", "GCH3CNHI", "GCH3OHI", "GH2COI", "GH2S2I", "GHClI", "GHCNI", "GH2CSI", "GH2OI", "GH2SI", "C4NI", "C3H2I", "H2S2I", "GNH3I", "H2NOII", "H2SiOI", "HClII", "HeHII", "HNCOI", "HNSII", "HOCII", "HSOII", "SiC3II", "GCH4I", "GSiH4I", "C4HI", "ClI", "ClII", "H2CNI", "C2N2II", "C4NII", "SiH5II", "H2ClII", "H5C2O2II", "SiC3I", "SiH4II", "C2H5OH2II", "C2NHII", "C3H5II", "CH2COI", "HSO2II", "C3NI", "HCOOCH3I", "SiC2II", "C3II", "H2S2II", "HClI", "HOCSII", "HS2I", "NSII", "CH3CCHI", "H3CSII", "SiC2I", "SO2II", "H2CSI", "H2CSII", "HC3NI", "HSiSII", "SiSII", "HS2II", "O2HI", "CH3CNHII", "NO2I", "S2II", "C2H5I", "C2H5OHI", "SiCII", "C2NI", "NCCNI", "SiCI", "HCSI", "SiH2I", "SiH3II", "SiSI", "CH3OH2II", "OCNI", "S2I", "SiH3I", "CH3CNI", "NSI", "OCSII", "SiH2II", "SO2I", "HNOI", "SiHI", "SiOII", "SiOHII", "SiHII", "SiH4I", "C2H3I", "C2NII", "HCO2II", "CSII", "HCSII", "SiOI", "CH3OHI", "H3SII", "SOI", "C2H4I", "CH4II", "CSI", "MgI", "MgII", "SOII", "C2II", "O2HII", "CNII", "N2HII", "OCSI", "H2SII", "HNOII", "CH5II", "N2II", "HSI", "HCNHII", "H2II", "H3COII", "SiI", "C2H2I", "HCNII", "HNCI", "SiII", "COII", "HSII", "CO2I", "NHII", "NH2I", "O2II", "NII", "NH2II", "C2HII", "NH4II", "C2HI", "OII", "NOII", "H2COII", "CH2II", "NH3II", "H2SI", "H2OII", "OHII", "CH3II", "N2I", "C2H2II", "C2I", "CH2I", "CH3I", "CHII", "NHI", "SII", "CNI", "H2COI", "CH4I", "HCOI", "HCNI", "NOI", "CHI", "NH3I", "H3OII", "O2I", "CII", "SI", "OHI", "NI", "HeII", "HeI", "H3II", "HII", "OI", "CI", "HCOII", "H2OI", "COI", "H2I", "EM", "HI"]
list_of_gas_species = ["CH3CNH", "C4N", "C3H2", "H2S2", "H2NO+", "H2SIO", "HCL+", "HEH+", "HNCO", "HNS+", "HOC+", "HSO+", "SIC3+", "C4H", "CL", "CL+", "H2CN", "C2N2+", "C4N+", "SIH5+", "H2CL+", "H5C2O2+", "SIC3", "SIH4+", "C2H5OH2+", "C2NH+", "C3H5+", "CH2CO", "HSO2+", "C3N", "HCOOCH3", "SIC2+", "C3+", "H2S2+", "HCL", "HOCS+", "HS2", "NS+", "CH3CCH", "H3CS+", "SIC2", "SO2+", "H2CS", "H2CS+", "HC3N", "HSIS+", "SIS+", "HS2+", "O2H", "CH3CNH+", "NO2", "S2+", "C2H5", "C2H5OH", "SIC+", "C2N", "NCCN", "SIC", "HCS", "SIH2", "SIH3+", "SIS", "CH3OH2+", "OCN", "S2", "SIH3", "CH3CN", "NS", "OCS+", "SIH2+", "SO2", "HNO", "SIH", "SIO+", "SIOH+", "SIH+", "SIH4", "C2H3", "C2N+", "HCO2+", "CS+", "HCS+", "SIO", "CH3OH", "H3S+", "SO", "C2H4", "CH4+", "CS", "MG", "MG+", "SO+", "C2+", "O2H+", "CN+", "N2H+", "OCS", "H2S+", "HNO+", "CH5+", "N2+", "HS", "HCNH+", "H2+", "H3CO+", "SI", "C2H2", "HCN+", "HNC", "SI+", "CO+", "HS+", "CO2", "NH+", "NH2", "O2+", "N+", "NH2+", "C2H+", "NH4+", "C2H", "O+", "NO+", "H2CO+", "CH2+", "NH3+", "H2S", "H2O+", "OH+", "CH3+", "N2", "C2H2+", "C2", "CH2", "CH3", "CH+", "NH", "S+", "CN", "H2CO", "CH4", "HCO", "HCN", "NO", "CH", "NH3", "H3O+", "O2", "C+", "S", "OH", "N", "HE+", "HE", "H3+", "H+", "O", "C", "HCO+", "H2O", "CO", "H2", "E-", "H"]
list_of_ice_species = ["#C2H3", "#C2H4", "#C2H5", "#C3H2", "#C4H", "#CH2CO", "#CH3CN", "#CS", "#H2CN", "#HNC", "#NO2", "#SIO", "#C2H", "#C2H2", "#C4N", "#CO", "#HC3N", "#HNCO", "#MG", "#NCCN", "#NO", "#O2", "#O2H", "#SIC", "#SIC2", "#SIC3", "#C2H5OH", "#CH3CCH", "#CO2", "#HCOOCH3", "#C2", "#H2SIO", "#HNO", "#N2", "#NS", "#OCS", "#SIS", "#SO", "#SO2", "#CH3CNH", "#CH3OH", "#H2CO", "#H2S2", "#HCL", "#HCN", "#H2CS", "#H2O", "#H2S", "#NH3", "#CH4", "#SIH4"]
list_of_grain_species = []

