# Naunet config document

[general]
creation_time = "01/02/2022 10:16:14"
name = "naunet_klu_cloud_custom"
description = "example"

[chemistry]
elements = ["E", "H", "D", "HE", "C", "N", "O", "MG", "SI", "S", "CL"]
pseudo_elements = ["CR", "CRP", "PHOTON", "CRPHOT"]
species = ["#C2", "#C2H", "#C2H2", "#C2H3", "#C2H4", "#C2H5", "#C2H5OH", "#C3H2", "#C4H", "#C4N", "#CH2CO", "#CH3CCH", "#CH3CN", "#CH3CNH", "#CH3OH", "#CH4", "#CO", "#CO2", "#CS", "#H2CN", "#H2CO", "#H2CS", "#H2O", "#H2S", "#H2S2", "#H2SIO", "#HC3N", "#HCL", "#HCN", "#HCOOCH3", "#HNC", "#HNCO", "#HNO", "#MG", "#N2", "#NCCN", "#NH3", "#NO", "#NO2", "#NS", "#O2", "#O2H", "#OCS", "#SIC", "#SIC2", "#SIC3", "#SIH4", "#SIO", "#SIS", "#SO", "#SO2", "C", "C+", "C2", "C2+", "C2H", "C2H+", "C2H2", "C2H2+", "C2H3", "C2H4", "C2H5", "C2H5OH", "C2H5OH2+", "C2N", "C2N+", "C2N2+", "C2NH+", "C3+", "C3H2", "C3H5+", "C3N", "C4H", "C4N", "C4N+", "CH", "CH+", "CH2", "CH2+", "CH2CO", "CH3", "CH3+", "CH3CCH", "CH3CN", "CH3CNH", "CH3CNH+", "CH3OH", "CH3OH2+", "CH4", "CH4+", "CH5+", "CL", "CL+", "CN", "CN+", "CO", "CO+", "CO2", "CS", "CS+", "E-", "H", "H+", "H2", "H2+", "H2CL+", "H2CN", "H2CO", "H2CO+", "H2CS", "H2CS+", "H2NO+", "H2O", "H2O+", "H2S", "H2S+", "H2S2", "H2S2+", "H2SIO", "H3+", "H3CO+", "H3CS+", "H3O+", "H3S+", "H5C2O2+", "HC3N", "HCL", "HCL+", "HCN", "HCN+", "HCNH+", "HCO", "HCO+", "HCO2+", "HCOOCH3", "HCS", "HCS+", "HE", "HE+", "HEH+", "HNC", "HNCO", "HNO", "HNO+", "HNS+", "HOC+", "HOCS+", "HS", "HS+", "HS2", "HS2+", "HSIS+", "HSO+", "HSO2+", "MG", "MG+", "N", "N+", "N2", "N2+", "N2H+", "NCCN", "NH", "NH+", "NH2", "NH2+", "NH3", "NH3+", "NH4+", "NO", "NO+", "NO2", "NS", "NS+", "O", "O+", "O2", "O2+", "O2H", "O2H+", "OCN", "OCS", "OCS+", "OH", "OH+", "S", "S+", "S2", "S2+", "SI", "SI+", "SIC", "SIC+", "SIC2", "SIC2+", "SIC3", "SIC3+", "SIH", "SIH+", "SIH2", "SIH2+", "SIH3", "SIH3+", "SIH4", "SIH4+", "SIH5+", "SIO", "SIO+", "SIOH+", "SIS", "SIS+", "SO", "SO+", "SO2", "SO2+"]
extra_species = []
network = ["reactions.ucl"]
database = ["uclcustreaction"]
heating = []
cooling = []
ode_modifier = ["ydot[IDX_H2I] += H2formation*y[IDX_HI]*nH - H2dissociation*y[IDX_H2I]", "ydot[IDX_HI] += 2.0*(H2dissociation*y[IDX_H2I] - H2formation*y[IDX_HI]*nH)"]

[chemistry.dust]
type = "RR07custom"

[chemistry.binding_energy]
"#CH4" = 960.0
"#NH3" = 5500.0
"#H2O" = 5600.0
"#C2" = 10000.0
"#MG" = 5300.0
"#C2H" = 3000.0
"#C2H2" = 2587.0
"#HCN" = 3700.0
"#HNC" = 3800.0
"#C2H3" = 2800.0
"#CO" = 1300.0
"#N2" = 1100.0
"#C2H4" = 2500.0
"#H2CN" = 2400.0
"#C2H5" = 3100.0
"#NO" = 1600.0
"#H2CO" = 4500.0
"#HNO" = 3000.0
"#O2" = 1200.0
"#CH3OH" = 5000.0
"#SIH4" = 13000.0
"#O2H" = 5000.0
"#H2S" = 2700.0
"#HCL" = 5172.0
"#C3H2" = 5900.0
"#CH3CCH" = 3000.0
"#SIC" = 3500.0
"#CH3CN" = 4680.0
"#CH2CO" = 2800.0
"#CH3CNH" = 3740.0
"#HNCO" = 4400.0
"#SIO" = 3500.0
"#CS" = 3200.0
"#CO2" = 2600.0
"#C2H5OH" = 5400.0
"#H2CS" = 4400.0
"#NO2" = 2400.0
"#NS" = 1900.0
"#H2SIO" = 4400.0
"#SO" = 2800.0
"#C4H" = 3737.0
"#HC3N" = 4580.0
"#NCCN" = 3000.0
"#SIC2" = 4300.0
"#HCOOCH3" = 4210.0
"#SIS" = 3800.0
"#OCS" = 2400.0
"#C4N" = 4000.0
"#SIC3" = 5100.0
"#SO2" = 3400.0
"#H2S2" = 3100.0

[chemistry.photon_yield]

[chemistry.shielding]
CO = "VB88Table"

[chemistry.rate_modifier]

[ODEsolver]
solver = "cvode"
device = "cpu"
method = "sparse"

[summary]
num_of_species = 215
num_of_gas_species = 164
num_of_ice_species = 51
num_of_reactions = 2507
list_of_species = ["#C2", "#C2H", "#C2H2", "#C2H3", "#C2H4", "#C2H5", "#C2H5OH", "#C3H2", "#C4H", "#C4N", "#CH2CO", "#CH3CCH", "#CH3CN", "#CH3CNH", "#CH3OH", "#CH4", "#CO", "#CO2", "#CS", "#H2CN", "#H2CO", "#H2CS", "#H2O", "#H2S", "#H2S2", "#H2SIO", "#HC3N", "#HCL", "#HCN", "#HCOOCH3", "#HNC", "#HNCO", "#HNO", "#MG", "#N2", "#NCCN", "#NH3", "#NO", "#NO2", "#NS", "#O2", "#O2H", "#OCS", "#SIC", "#SIC2", "#SIC3", "#SIH4", "#SIO", "#SIS", "#SO", "#SO2", "C", "C+", "C2", "C2+", "C2H", "C2H+", "C2H2", "C2H2+", "C2H3", "C2H4", "C2H5", "C2H5OH", "C2H5OH2+", "C2N", "C2N+", "C2N2+", "C2NH+", "C3+", "C3H2", "C3H5+", "C3N", "C4H", "C4N", "C4N+", "CH", "CH+", "CH2", "CH2+", "CH2CO", "CH3", "CH3+", "CH3CCH", "CH3CN", "CH3CNH", "CH3CNH+", "CH3OH", "CH3OH2+", "CH4", "CH4+", "CH5+", "CL", "CL+", "CN", "CN+", "CO", "CO+", "CO2", "CS", "CS+", "E-", "H", "H+", "H2", "H2+", "H2CL+", "H2CN", "H2CO", "H2CO+", "H2CS", "H2CS+", "H2NO+", "H2O", "H2O+", "H2S", "H2S+", "H2S2", "H2S2+", "H2SIO", "H3+", "H3CO+", "H3CS+", "H3O+", "H3S+", "H5C2O2+", "HC3N", "HCL", "HCL+", "HCN", "HCN+", "HCNH+", "HCO", "HCO+", "HCO2+", "HCOOCH3", "HCS", "HCS+", "HE", "HE+", "HEH+", "HNC", "HNCO", "HNO", "HNO+", "HNS+", "HOC+", "HOCS+", "HS", "HS+", "HS2", "HS2+", "HSIS+", "HSO+", "HSO2+", "MG", "MG+", "N", "N+", "N2", "N2+", "N2H+", "NCCN", "NH", "NH+", "NH2", "NH2+", "NH3", "NH3+", "NH4+", "NO", "NO+", "NO2", "NS", "NS+", "O", "O+", "O2", "O2+", "O2H", "O2H+", "OCN", "OCS", "OCS+", "OH", "OH+", "S", "S+", "S2", "S2+", "SI", "SI+", "SIC", "SIC+", "SIC2", "SIC2+", "SIC3", "SIC3+", "SIH", "SIH+", "SIH2", "SIH2+", "SIH3", "SIH3+", "SIH4", "SIH4+", "SIH5+", "SIO", "SIO+", "SIOH+", "SIS", "SIS+", "SO", "SO+", "SO2", "SO2+"]
list_of_species_alias = ["GC2I", "GC2HI", "GC2H2I", "GC2H3I", "GC2H4I", "GC2H5I", "GC2H5OHI", "GC3H2I", "GC4HI", "GC4NI", "GCH2COI", "GCH3CCHI", "GCH3CNI", "GCH3CNHI", "GCH3OHI", "GCH4I", "GCOI", "GCO2I", "GCSI", "GH2CNI", "GH2COI", "GH2CSI", "GH2OI", "GH2SI", "GH2S2I", "GH2SiOI", "GHC3NI", "GHClI", "GHCNI", "GHCOOCH3I", "GHNCI", "GHNCOI", "GHNOI", "GMgI", "GN2I", "GNCCNI", "GNH3I", "GNOI", "GNO2I", "GNSI", "GO2I", "GO2HI", "GOCSI", "GSiCI", "GSiC2I", "GSiC3I", "GSiH4I", "GSiOI", "GSiSI", "GSOI", "GSO2I", "CI", "CII", "C2I", "C2II", "C2HI", "C2HII", "C2H2I", "C2H2II", "C2H3I", "C2H4I", "C2H5I", "C2H5OHI", "C2H5OH2II", "C2NI", "C2NII", "C2N2II", "C2NHII", "C3II", "C3H2I", "C3H5II", "C3NI", "C4HI", "C4NI", "C4NII", "CHI", "CHII", "CH2I", "CH2II", "CH2COI", "CH3I", "CH3II", "CH3CCHI", "CH3CNI", "CH3CNHI", "CH3CNHII", "CH3OHI", "CH3OH2II", "CH4I", "CH4II", "CH5II", "ClI", "ClII", "CNI", "CNII", "COI", "COII", "CO2I", "CSI", "CSII", "EM", "HI", "HII", "H2I", "H2II", "H2ClII", "H2CNI", "H2COI", "H2COII", "H2CSI", "H2CSII", "H2NOII", "H2OI", "H2OII", "H2SI", "H2SII", "H2S2I", "H2S2II", "H2SiOI", "H3II", "H3COII", "H3CSII", "H3OII", "H3SII", "H5C2O2II", "HC3NI", "HClI", "HClII", "HCNI", "HCNII", "HCNHII", "HCOI", "HCOII", "HCO2II", "HCOOCH3I", "HCSI", "HCSII", "HeI", "HeII", "HeHII", "HNCI", "HNCOI", "HNOI", "HNOII", "HNSII", "HOCII", "HOCSII", "HSI", "HSII", "HS2I", "HS2II", "HSiSII", "HSOII", "HSO2II", "MgI", "MgII", "NI", "NII", "N2I", "N2II", "N2HII", "NCCNI", "NHI", "NHII", "NH2I", "NH2II", "NH3I", "NH3II", "NH4II", "NOI", "NOII", "NO2I", "NSI", "NSII", "OI", "OII", "O2I", "O2II", "O2HI", "O2HII", "OCNI", "OCSI", "OCSII", "OHI", "OHII", "SI", "SII", "S2I", "S2II", "SiI", "SiII", "SiCI", "SiCII", "SiC2I", "SiC2II", "SiC3I", "SiC3II", "SiHI", "SiHII", "SiH2I", "SiH2II", "SiH3I", "SiH3II", "SiH4I", "SiH4II", "SiH5II", "SiOI", "SiOII", "SiOHII", "SiSI", "SiSII", "SOI", "SOII", "SO2I", "SO2II"]
list_of_gas_species = ["C", "C+", "C2", "C2+", "C2H", "C2H+", "C2H2", "C2H2+", "C2H3", "C2H4", "C2H5", "C2H5OH", "C2H5OH2+", "C2N", "C2N+", "C2N2+", "C2NH+", "C3+", "C3H2", "C3H5+", "C3N", "C4H", "C4N", "C4N+", "CH", "CH+", "CH2", "CH2+", "CH2CO", "CH3", "CH3+", "CH3CCH", "CH3CN", "CH3CNH", "CH3CNH+", "CH3OH", "CH3OH2+", "CH4", "CH4+", "CH5+", "CL", "CL+", "CN", "CN+", "CO", "CO+", "CO2", "CS", "CS+", "E-", "H", "H+", "H2", "H2+", "H2CL+", "H2CN", "H2CO", "H2CO+", "H2CS", "H2CS+", "H2NO+", "H2O", "H2O+", "H2S", "H2S+", "H2S2", "H2S2+", "H2SIO", "H3+", "H3CO+", "H3CS+", "H3O+", "H3S+", "H5C2O2+", "HC3N", "HCL", "HCL+", "HCN", "HCN+", "HCNH+", "HCO", "HCO+", "HCO2+", "HCOOCH3", "HCS", "HCS+", "HE", "HE+", "HEH+", "HNC", "HNCO", "HNO", "HNO+", "HNS+", "HOC+", "HOCS+", "HS", "HS+", "HS2", "HS2+", "HSIS+", "HSO+", "HSO2+", "MG", "MG+", "N", "N+", "N2", "N2+", "N2H+", "NCCN", "NH", "NH+", "NH2", "NH2+", "NH3", "NH3+", "NH4+", "NO", "NO+", "NO2", "NS", "NS+", "O", "O+", "O2", "O2+", "O2H", "O2H+", "OCN", "OCS", "OCS+", "OH", "OH+", "S", "S+", "S2", "S2+", "SI", "SI+", "SIC", "SIC+", "SIC2", "SIC2+", "SIC3", "SIC3+", "SIH", "SIH+", "SIH2", "SIH2+", "SIH3", "SIH3+", "SIH4", "SIH4+", "SIH5+", "SIO", "SIO+", "SIOH+", "SIS", "SIS+", "SO", "SO+", "SO2", "SO2+"]
list_of_ice_species = ["#C2", "#C2H", "#C2H2", "#C2H3", "#C2H4", "#C2H5", "#C2H5OH", "#C3H2", "#C4H", "#C4N", "#CH2CO", "#CH3CCH", "#CH3CN", "#CH3CNH", "#CH3OH", "#CH4", "#CO", "#CO2", "#CS", "#H2CN", "#H2CO", "#H2CS", "#H2O", "#H2S", "#H2S2", "#H2SIO", "#HC3N", "#HCL", "#HCN", "#HCOOCH3", "#HNC", "#HNCO", "#HNO", "#MG", "#N2", "#NCCN", "#NH3", "#NO", "#NO2", "#NS", "#O2", "#O2H", "#OCS", "#SIC", "#SIC2", "#SIC3", "#SIH4", "#SIO", "#SIS", "#SO", "#SO2"]

