/***********************************************************************
/
/  GRID CLASS (IDENTIFY THE MULTI-SPECIES FIELDS)
/
/  written by: Chia-Jung Hsu, Patch generated by naunet
/  date:       2021
/
************************************************************************/
// clang-format off
#include "preincludes.h"
#ifdef USE_NAUNET
#include "naunet_enzo.h"
#endif
#include "macros_and_parameters.h"
#include "typedefs.h"
#include "global_data.h"
#include "Fluxes.h"
#include "GridList.h"
#include "ExternalBoundary.h"
#include "Grid.h"

/* function prototypes */

int FindField(int f, int farray[], int n);

#ifdef USE_NAUNET


int grid::IdentifyNaunetSpeciesFields(int &GH2CNINum, int &GHNCINum, int
                                      &GNO2INum, int &GSiOINum, int &GCOINum,
                                      int &GHNCOINum, int &GMgINum, int
                                      &GNOINum, int &GO2INum, int &GO2HINum, int
                                      &GSiCINum, int &GSiC2INum, int &GSiC3INum,
                                      int &GCH3OHINum, int &GCO2INum, int
                                      &GH2SiOINum, int &GHNOINum, int &GN2INum,
                                      int &GH2COINum, int &GHCNINum, int
                                      &GH2OINum, int &GNH3INum, int &SiC3IINum,
                                      int &H2CNINum, int &GCH4INum, int
                                      &H2NOIINum, int &H2SiOINum, int &HeHIINum,
                                      int &HNCOINum, int &HOCIINum, int
                                      &SiC2IINum, int &GSiH4INum, int &SiC2INum,
                                      int &SiC3INum, int &SiH5IINum, int
                                      &SiH4IINum, int &SiCIINum, int &O2HINum,
                                      int &SiCINum, int &NO2INum, int
                                      &SiH3IINum, int &SiH2IINum, int &OCNINum,
                                      int &SiH2INum, int &SiOHIINum, int
                                      &SiHIINum, int &SiH4INum, int &SiHINum,
                                      int &SiH3INum, int &SiOIINum, int
                                      &HCO2IINum, int &HNOINum, int &CH3OHINum,
                                      int &MgINum, int &MgIINum, int &CH4IINum,
                                      int &SiOINum, int &CNIINum, int
                                      &HCNHIINum, int &N2HIINum, int &O2HIINum,
                                      int &SiIINum, int &SiINum, int &HNCINum,
                                      int &HNOIINum, int &N2IINum, int
                                      &H3COIINum, int &CH4INum, int &COIINum,
                                      int &H2IINum, int &NH3INum, int &CH3INum,
                                      int &CO2INum, int &NIINum, int &OIINum,
                                      int &HCNIINum, int &NH2IINum, int
                                      &NHIINum, int &O2IINum, int &CH3IINum, int
                                      &NH2INum, int &CH2IINum, int &H2OIINum,
                                      int &NH3IINum, int &NOIINum, int
                                      &H3OIINum, int &N2INum, int &CIINum, int
                                      &HCNINum, int &CHIINum, int &CH2INum, int
                                      &H2COIINum, int &NHINum, int &OHIINum, int
                                      &CNINum, int &H2COINum, int &HCOINum, int
                                      &HeIINum, int &CHINum, int &H3IINum, int
                                      &HeINum, int &NOINum, int &NINum, int
                                      &OHINum, int &O2INum, int &CINum, int
                                      &HIINum, int &HCOIINum, int &H2OINum, int
                                      &OINum, int &DeNum, int &COINum, int
                                      &H2INum, int &HINum)
{
    GH2CNINum = GHNCINum = GNO2INum = GSiOINum = GCOINum = GHNCOINum = GMgINum =
    GNOINum = GO2INum = GO2HINum = GSiCINum = GSiC2INum = GSiC3INum = GCH3OHINum
    = GCO2INum = GH2SiOINum = GHNOINum = GN2INum = GH2COINum = GHCNINum =
    GH2OINum = GNH3INum = SiC3IINum = H2CNINum = GCH4INum = H2NOIINum =
    H2SiOINum = HeHIINum = HNCOINum = HOCIINum = SiC2IINum = GSiH4INum =
    SiC2INum = SiC3INum = SiH5IINum = SiH4IINum = SiCIINum = O2HINum = SiCINum =
    NO2INum = SiH3IINum = SiH2IINum = OCNINum = SiH2INum = SiOHIINum = SiHIINum
    = SiH4INum = SiHINum = SiH3INum = SiOIINum = HCO2IINum = HNOINum = CH3OHINum
    = MgINum = MgIINum = CH4IINum = SiOINum = CNIINum = HCNHIINum = N2HIINum =
    O2HIINum = SiIINum = SiINum = HNCINum = HNOIINum = N2IINum = H3COIINum =
    CH4INum = COIINum = H2IINum = NH3INum = CH3INum = CO2INum = NIINum = OIINum
    = HCNIINum = NH2IINum = NHIINum = O2IINum = CH3IINum = NH2INum = CH2IINum =
    H2OIINum = NH3IINum = NOIINum = H3OIINum = N2INum = CIINum = HCNINum =
    CHIINum = CH2INum = H2COIINum = NHINum = OHIINum = CNINum = H2COINum =
    HCOINum = HeIINum = CHINum = H3IINum = HeINum = NOINum = NINum = OHINum =
    O2INum = CINum = HIINum = HCOIINum = H2OINum = OINum = DeNum = COINum =
    H2INum = HINum = 0;

    // Find Fields for the Naunet species
    GH2CNINum = FindField(GH2CNIDensity, FieldType, NumberOfBaryonFields);
    GHNCINum = FindField(GHNCIDensity, FieldType, NumberOfBaryonFields);
    GNO2INum = FindField(GNO2IDensity, FieldType, NumberOfBaryonFields);
    GSiOINum = FindField(GSiOIDensity, FieldType, NumberOfBaryonFields);
    GCOINum = FindField(GCOIDensity, FieldType, NumberOfBaryonFields);
    GHNCOINum = FindField(GHNCOIDensity, FieldType, NumberOfBaryonFields);
    GMgINum = FindField(GMgIDensity, FieldType, NumberOfBaryonFields);
    GNOINum = FindField(GNOIDensity, FieldType, NumberOfBaryonFields);
    GO2INum = FindField(GO2IDensity, FieldType, NumberOfBaryonFields);
    GO2HINum = FindField(GO2HIDensity, FieldType, NumberOfBaryonFields);
    GSiCINum = FindField(GSiCIDensity, FieldType, NumberOfBaryonFields);
    GSiC2INum = FindField(GSiC2IDensity, FieldType, NumberOfBaryonFields);
    GSiC3INum = FindField(GSiC3IDensity, FieldType, NumberOfBaryonFields);
    GCH3OHINum = FindField(GCH3OHIDensity, FieldType, NumberOfBaryonFields);
    GCO2INum = FindField(GCO2IDensity, FieldType, NumberOfBaryonFields);
    GH2SiOINum = FindField(GH2SiOIDensity, FieldType, NumberOfBaryonFields);
    GHNOINum = FindField(GHNOIDensity, FieldType, NumberOfBaryonFields);
    GN2INum = FindField(GN2IDensity, FieldType, NumberOfBaryonFields);
    GH2COINum = FindField(GH2COIDensity, FieldType, NumberOfBaryonFields);
    GHCNINum = FindField(GHCNIDensity, FieldType, NumberOfBaryonFields);
    GH2OINum = FindField(GH2OIDensity, FieldType, NumberOfBaryonFields);
    GNH3INum = FindField(GNH3IDensity, FieldType, NumberOfBaryonFields);
    SiC3IINum = FindField(SiC3IIDensity, FieldType, NumberOfBaryonFields);
    H2CNINum = FindField(H2CNIDensity, FieldType, NumberOfBaryonFields);
    GCH4INum = FindField(GCH4IDensity, FieldType, NumberOfBaryonFields);
    H2NOIINum = FindField(H2NOIIDensity, FieldType, NumberOfBaryonFields);
    H2SiOINum = FindField(H2SiOIDensity, FieldType, NumberOfBaryonFields);
    HeHIINum = FindField(HeHIIDensity, FieldType, NumberOfBaryonFields);
    HNCOINum = FindField(HNCOIDensity, FieldType, NumberOfBaryonFields);
    HOCIINum = FindField(HOCIIDensity, FieldType, NumberOfBaryonFields);
    SiC2IINum = FindField(SiC2IIDensity, FieldType, NumberOfBaryonFields);
    GSiH4INum = FindField(GSiH4IDensity, FieldType, NumberOfBaryonFields);
    SiC2INum = FindField(SiC2IDensity, FieldType, NumberOfBaryonFields);
    SiC3INum = FindField(SiC3IDensity, FieldType, NumberOfBaryonFields);
    SiH5IINum = FindField(SiH5IIDensity, FieldType, NumberOfBaryonFields);
    SiH4IINum = FindField(SiH4IIDensity, FieldType, NumberOfBaryonFields);
    SiCIINum = FindField(SiCIIDensity, FieldType, NumberOfBaryonFields);
    O2HINum = FindField(O2HIDensity, FieldType, NumberOfBaryonFields);
    SiCINum = FindField(SiCIDensity, FieldType, NumberOfBaryonFields);
    NO2INum = FindField(NO2IDensity, FieldType, NumberOfBaryonFields);
    SiH3IINum = FindField(SiH3IIDensity, FieldType, NumberOfBaryonFields);
    SiH2IINum = FindField(SiH2IIDensity, FieldType, NumberOfBaryonFields);
    OCNINum = FindField(OCNIDensity, FieldType, NumberOfBaryonFields);
    SiH2INum = FindField(SiH2IDensity, FieldType, NumberOfBaryonFields);
    SiOHIINum = FindField(SiOHIIDensity, FieldType, NumberOfBaryonFields);
    SiHIINum = FindField(SiHIIDensity, FieldType, NumberOfBaryonFields);
    SiH4INum = FindField(SiH4IDensity, FieldType, NumberOfBaryonFields);
    SiHINum = FindField(SiHIDensity, FieldType, NumberOfBaryonFields);
    SiH3INum = FindField(SiH3IDensity, FieldType, NumberOfBaryonFields);
    SiOIINum = FindField(SiOIIDensity, FieldType, NumberOfBaryonFields);
    HCO2IINum = FindField(HCO2IIDensity, FieldType, NumberOfBaryonFields);
    HNOINum = FindField(HNOIDensity, FieldType, NumberOfBaryonFields);
    CH3OHINum = FindField(CH3OHIDensity, FieldType, NumberOfBaryonFields);
    MgINum = FindField(MgIDensity, FieldType, NumberOfBaryonFields);
    MgIINum = FindField(MgIIDensity, FieldType, NumberOfBaryonFields);
    CH4IINum = FindField(CH4IIDensity, FieldType, NumberOfBaryonFields);
    SiOINum = FindField(SiOIDensity, FieldType, NumberOfBaryonFields);
    CNIINum = FindField(CNIIDensity, FieldType, NumberOfBaryonFields);
    HCNHIINum = FindField(HCNHIIDensity, FieldType, NumberOfBaryonFields);
    N2HIINum = FindField(N2HIIDensity, FieldType, NumberOfBaryonFields);
    O2HIINum = FindField(O2HIIDensity, FieldType, NumberOfBaryonFields);
    SiIINum = FindField(SiIIDensity, FieldType, NumberOfBaryonFields);
    SiINum = FindField(SiIDensity, FieldType, NumberOfBaryonFields);
    HNCINum = FindField(HNCIDensity, FieldType, NumberOfBaryonFields);
    HNOIINum = FindField(HNOIIDensity, FieldType, NumberOfBaryonFields);
    N2IINum = FindField(N2IIDensity, FieldType, NumberOfBaryonFields);
    H3COIINum = FindField(H3COIIDensity, FieldType, NumberOfBaryonFields);
    CH4INum = FindField(CH4IDensity, FieldType, NumberOfBaryonFields);
    COIINum = FindField(COIIDensity, FieldType, NumberOfBaryonFields);
    H2IINum = FindField(H2IIDensity, FieldType, NumberOfBaryonFields);
    NH3INum = FindField(NH3IDensity, FieldType, NumberOfBaryonFields);
    CH3INum = FindField(CH3IDensity, FieldType, NumberOfBaryonFields);
    CO2INum = FindField(CO2IDensity, FieldType, NumberOfBaryonFields);
    NIINum = FindField(NIIDensity, FieldType, NumberOfBaryonFields);
    OIINum = FindField(OIIDensity, FieldType, NumberOfBaryonFields);
    HCNIINum = FindField(HCNIIDensity, FieldType, NumberOfBaryonFields);
    NH2IINum = FindField(NH2IIDensity, FieldType, NumberOfBaryonFields);
    NHIINum = FindField(NHIIDensity, FieldType, NumberOfBaryonFields);
    O2IINum = FindField(O2IIDensity, FieldType, NumberOfBaryonFields);
    CH3IINum = FindField(CH3IIDensity, FieldType, NumberOfBaryonFields);
    NH2INum = FindField(NH2IDensity, FieldType, NumberOfBaryonFields);
    CH2IINum = FindField(CH2IIDensity, FieldType, NumberOfBaryonFields);
    H2OIINum = FindField(H2OIIDensity, FieldType, NumberOfBaryonFields);
    NH3IINum = FindField(NH3IIDensity, FieldType, NumberOfBaryonFields);
    NOIINum = FindField(NOIIDensity, FieldType, NumberOfBaryonFields);
    H3OIINum = FindField(H3OIIDensity, FieldType, NumberOfBaryonFields);
    N2INum = FindField(N2IDensity, FieldType, NumberOfBaryonFields);
    CIINum = FindField(CIIDensity, FieldType, NumberOfBaryonFields);
    HCNINum = FindField(HCNIDensity, FieldType, NumberOfBaryonFields);
    CHIINum = FindField(CHIIDensity, FieldType, NumberOfBaryonFields);
    CH2INum = FindField(CH2IDensity, FieldType, NumberOfBaryonFields);
    H2COIINum = FindField(H2COIIDensity, FieldType, NumberOfBaryonFields);
    NHINum = FindField(NHIDensity, FieldType, NumberOfBaryonFields);
    OHIINum = FindField(OHIIDensity, FieldType, NumberOfBaryonFields);
    CNINum = FindField(CNIDensity, FieldType, NumberOfBaryonFields);
    H2COINum = FindField(H2COIDensity, FieldType, NumberOfBaryonFields);
    HCOINum = FindField(HCOIDensity, FieldType, NumberOfBaryonFields);
    HeIINum = FindField(HeIIDensity, FieldType, NumberOfBaryonFields);
    CHINum = FindField(CHIDensity, FieldType, NumberOfBaryonFields);
    H3IINum = FindField(H3IIDensity, FieldType, NumberOfBaryonFields);
    HeINum = FindField(HeIDensity, FieldType, NumberOfBaryonFields);
    NOINum = FindField(NOIDensity, FieldType, NumberOfBaryonFields);
    NINum = FindField(NIDensity, FieldType, NumberOfBaryonFields);
    OHINum = FindField(OHIDensity, FieldType, NumberOfBaryonFields);
    O2INum = FindField(O2IDensity, FieldType, NumberOfBaryonFields);
    CINum = FindField(CIDensity, FieldType, NumberOfBaryonFields);
    HIINum = FindField(HIIDensity, FieldType, NumberOfBaryonFields);
    HCOIINum = FindField(HCOIIDensity, FieldType, NumberOfBaryonFields);
    H2OINum = FindField(H2OIDensity, FieldType, NumberOfBaryonFields);
    OINum = FindField(OIDensity, FieldType, NumberOfBaryonFields);
    DeNum = FindField(ElectronDensity, FieldType, NumberOfBaryonFields);
    COINum = FindField(COIDensity, FieldType, NumberOfBaryonFields);
    H2INum = FindField(H2IDensity, FieldType, NumberOfBaryonFields);
    HINum = FindField(HIDensity, FieldType, NumberOfBaryonFields);
    // check fields exist
    if (GH2CNINum < 0) ENZO_VFAIL("GH2CNINum=%" ISYM "\n", GH2CNINum);
    if (GHNCINum < 0) ENZO_VFAIL("GHNCINum=%" ISYM "\n", GHNCINum);
    if (GNO2INum < 0) ENZO_VFAIL("GNO2INum=%" ISYM "\n", GNO2INum);
    if (GSiOINum < 0) ENZO_VFAIL("GSiOINum=%" ISYM "\n", GSiOINum);
    if (GCOINum < 0) ENZO_VFAIL("GCOINum=%" ISYM "\n", GCOINum);
    if (GHNCOINum < 0) ENZO_VFAIL("GHNCOINum=%" ISYM "\n", GHNCOINum);
    if (GMgINum < 0) ENZO_VFAIL("GMgINum=%" ISYM "\n", GMgINum);
    if (GNOINum < 0) ENZO_VFAIL("GNOINum=%" ISYM "\n", GNOINum);
    if (GO2INum < 0) ENZO_VFAIL("GO2INum=%" ISYM "\n", GO2INum);
    if (GO2HINum < 0) ENZO_VFAIL("GO2HINum=%" ISYM "\n", GO2HINum);
    if (GSiCINum < 0) ENZO_VFAIL("GSiCINum=%" ISYM "\n", GSiCINum);
    if (GSiC2INum < 0) ENZO_VFAIL("GSiC2INum=%" ISYM "\n", GSiC2INum);
    if (GSiC3INum < 0) ENZO_VFAIL("GSiC3INum=%" ISYM "\n", GSiC3INum);
    if (GCH3OHINum < 0) ENZO_VFAIL("GCH3OHINum=%" ISYM "\n", GCH3OHINum);
    if (GCO2INum < 0) ENZO_VFAIL("GCO2INum=%" ISYM "\n", GCO2INum);
    if (GH2SiOINum < 0) ENZO_VFAIL("GH2SiOINum=%" ISYM "\n", GH2SiOINum);
    if (GHNOINum < 0) ENZO_VFAIL("GHNOINum=%" ISYM "\n", GHNOINum);
    if (GN2INum < 0) ENZO_VFAIL("GN2INum=%" ISYM "\n", GN2INum);
    if (GH2COINum < 0) ENZO_VFAIL("GH2COINum=%" ISYM "\n", GH2COINum);
    if (GHCNINum < 0) ENZO_VFAIL("GHCNINum=%" ISYM "\n", GHCNINum);
    if (GH2OINum < 0) ENZO_VFAIL("GH2OINum=%" ISYM "\n", GH2OINum);
    if (GNH3INum < 0) ENZO_VFAIL("GNH3INum=%" ISYM "\n", GNH3INum);
    if (SiC3IINum < 0) ENZO_VFAIL("SiC3IINum=%" ISYM "\n", SiC3IINum);
    if (H2CNINum < 0) ENZO_VFAIL("H2CNINum=%" ISYM "\n", H2CNINum);
    if (GCH4INum < 0) ENZO_VFAIL("GCH4INum=%" ISYM "\n", GCH4INum);
    if (H2NOIINum < 0) ENZO_VFAIL("H2NOIINum=%" ISYM "\n", H2NOIINum);
    if (H2SiOINum < 0) ENZO_VFAIL("H2SiOINum=%" ISYM "\n", H2SiOINum);
    if (HeHIINum < 0) ENZO_VFAIL("HeHIINum=%" ISYM "\n", HeHIINum);
    if (HNCOINum < 0) ENZO_VFAIL("HNCOINum=%" ISYM "\n", HNCOINum);
    if (HOCIINum < 0) ENZO_VFAIL("HOCIINum=%" ISYM "\n", HOCIINum);
    if (SiC2IINum < 0) ENZO_VFAIL("SiC2IINum=%" ISYM "\n", SiC2IINum);
    if (GSiH4INum < 0) ENZO_VFAIL("GSiH4INum=%" ISYM "\n", GSiH4INum);
    if (SiC2INum < 0) ENZO_VFAIL("SiC2INum=%" ISYM "\n", SiC2INum);
    if (SiC3INum < 0) ENZO_VFAIL("SiC3INum=%" ISYM "\n", SiC3INum);
    if (SiH5IINum < 0) ENZO_VFAIL("SiH5IINum=%" ISYM "\n", SiH5IINum);
    if (SiH4IINum < 0) ENZO_VFAIL("SiH4IINum=%" ISYM "\n", SiH4IINum);
    if (SiCIINum < 0) ENZO_VFAIL("SiCIINum=%" ISYM "\n", SiCIINum);
    if (O2HINum < 0) ENZO_VFAIL("O2HINum=%" ISYM "\n", O2HINum);
    if (SiCINum < 0) ENZO_VFAIL("SiCINum=%" ISYM "\n", SiCINum);
    if (NO2INum < 0) ENZO_VFAIL("NO2INum=%" ISYM "\n", NO2INum);
    if (SiH3IINum < 0) ENZO_VFAIL("SiH3IINum=%" ISYM "\n", SiH3IINum);
    if (SiH2IINum < 0) ENZO_VFAIL("SiH2IINum=%" ISYM "\n", SiH2IINum);
    if (OCNINum < 0) ENZO_VFAIL("OCNINum=%" ISYM "\n", OCNINum);
    if (SiH2INum < 0) ENZO_VFAIL("SiH2INum=%" ISYM "\n", SiH2INum);
    if (SiOHIINum < 0) ENZO_VFAIL("SiOHIINum=%" ISYM "\n", SiOHIINum);
    if (SiHIINum < 0) ENZO_VFAIL("SiHIINum=%" ISYM "\n", SiHIINum);
    if (SiH4INum < 0) ENZO_VFAIL("SiH4INum=%" ISYM "\n", SiH4INum);
    if (SiHINum < 0) ENZO_VFAIL("SiHINum=%" ISYM "\n", SiHINum);
    if (SiH3INum < 0) ENZO_VFAIL("SiH3INum=%" ISYM "\n", SiH3INum);
    if (SiOIINum < 0) ENZO_VFAIL("SiOIINum=%" ISYM "\n", SiOIINum);
    if (HCO2IINum < 0) ENZO_VFAIL("HCO2IINum=%" ISYM "\n", HCO2IINum);
    if (HNOINum < 0) ENZO_VFAIL("HNOINum=%" ISYM "\n", HNOINum);
    if (CH3OHINum < 0) ENZO_VFAIL("CH3OHINum=%" ISYM "\n", CH3OHINum);
    if (MgINum < 0) ENZO_VFAIL("MgINum=%" ISYM "\n", MgINum);
    if (MgIINum < 0) ENZO_VFAIL("MgIINum=%" ISYM "\n", MgIINum);
    if (CH4IINum < 0) ENZO_VFAIL("CH4IINum=%" ISYM "\n", CH4IINum);
    if (SiOINum < 0) ENZO_VFAIL("SiOINum=%" ISYM "\n", SiOINum);
    if (CNIINum < 0) ENZO_VFAIL("CNIINum=%" ISYM "\n", CNIINum);
    if (HCNHIINum < 0) ENZO_VFAIL("HCNHIINum=%" ISYM "\n", HCNHIINum);
    if (N2HIINum < 0) ENZO_VFAIL("N2HIINum=%" ISYM "\n", N2HIINum);
    if (O2HIINum < 0) ENZO_VFAIL("O2HIINum=%" ISYM "\n", O2HIINum);
    if (SiIINum < 0) ENZO_VFAIL("SiIINum=%" ISYM "\n", SiIINum);
    if (SiINum < 0) ENZO_VFAIL("SiINum=%" ISYM "\n", SiINum);
    if (HNCINum < 0) ENZO_VFAIL("HNCINum=%" ISYM "\n", HNCINum);
    if (HNOIINum < 0) ENZO_VFAIL("HNOIINum=%" ISYM "\n", HNOIINum);
    if (N2IINum < 0) ENZO_VFAIL("N2IINum=%" ISYM "\n", N2IINum);
    if (H3COIINum < 0) ENZO_VFAIL("H3COIINum=%" ISYM "\n", H3COIINum);
    if (CH4INum < 0) ENZO_VFAIL("CH4INum=%" ISYM "\n", CH4INum);
    if (COIINum < 0) ENZO_VFAIL("COIINum=%" ISYM "\n", COIINum);
    if (H2IINum < 0) ENZO_VFAIL("H2IINum=%" ISYM "\n", H2IINum);
    if (NH3INum < 0) ENZO_VFAIL("NH3INum=%" ISYM "\n", NH3INum);
    if (CH3INum < 0) ENZO_VFAIL("CH3INum=%" ISYM "\n", CH3INum);
    if (CO2INum < 0) ENZO_VFAIL("CO2INum=%" ISYM "\n", CO2INum);
    if (NIINum < 0) ENZO_VFAIL("NIINum=%" ISYM "\n", NIINum);
    if (OIINum < 0) ENZO_VFAIL("OIINum=%" ISYM "\n", OIINum);
    if (HCNIINum < 0) ENZO_VFAIL("HCNIINum=%" ISYM "\n", HCNIINum);
    if (NH2IINum < 0) ENZO_VFAIL("NH2IINum=%" ISYM "\n", NH2IINum);
    if (NHIINum < 0) ENZO_VFAIL("NHIINum=%" ISYM "\n", NHIINum);
    if (O2IINum < 0) ENZO_VFAIL("O2IINum=%" ISYM "\n", O2IINum);
    if (CH3IINum < 0) ENZO_VFAIL("CH3IINum=%" ISYM "\n", CH3IINum);
    if (NH2INum < 0) ENZO_VFAIL("NH2INum=%" ISYM "\n", NH2INum);
    if (CH2IINum < 0) ENZO_VFAIL("CH2IINum=%" ISYM "\n", CH2IINum);
    if (H2OIINum < 0) ENZO_VFAIL("H2OIINum=%" ISYM "\n", H2OIINum);
    if (NH3IINum < 0) ENZO_VFAIL("NH3IINum=%" ISYM "\n", NH3IINum);
    if (NOIINum < 0) ENZO_VFAIL("NOIINum=%" ISYM "\n", NOIINum);
    if (H3OIINum < 0) ENZO_VFAIL("H3OIINum=%" ISYM "\n", H3OIINum);
    if (N2INum < 0) ENZO_VFAIL("N2INum=%" ISYM "\n", N2INum);
    if (CIINum < 0) ENZO_VFAIL("CIINum=%" ISYM "\n", CIINum);
    if (HCNINum < 0) ENZO_VFAIL("HCNINum=%" ISYM "\n", HCNINum);
    if (CHIINum < 0) ENZO_VFAIL("CHIINum=%" ISYM "\n", CHIINum);
    if (CH2INum < 0) ENZO_VFAIL("CH2INum=%" ISYM "\n", CH2INum);
    if (H2COIINum < 0) ENZO_VFAIL("H2COIINum=%" ISYM "\n", H2COIINum);
    if (NHINum < 0) ENZO_VFAIL("NHINum=%" ISYM "\n", NHINum);
    if (OHIINum < 0) ENZO_VFAIL("OHIINum=%" ISYM "\n", OHIINum);
    if (CNINum < 0) ENZO_VFAIL("CNINum=%" ISYM "\n", CNINum);
    if (H2COINum < 0) ENZO_VFAIL("H2COINum=%" ISYM "\n", H2COINum);
    if (HCOINum < 0) ENZO_VFAIL("HCOINum=%" ISYM "\n", HCOINum);
    if (HeIINum < 0) ENZO_VFAIL("HeIINum=%" ISYM "\n", HeIINum);
    if (CHINum < 0) ENZO_VFAIL("CHINum=%" ISYM "\n", CHINum);
    if (H3IINum < 0) ENZO_VFAIL("H3IINum=%" ISYM "\n", H3IINum);
    if (HeINum < 0) ENZO_VFAIL("HeINum=%" ISYM "\n", HeINum);
    if (NOINum < 0) ENZO_VFAIL("NOINum=%" ISYM "\n", NOINum);
    if (NINum < 0) ENZO_VFAIL("NINum=%" ISYM "\n", NINum);
    if (OHINum < 0) ENZO_VFAIL("OHINum=%" ISYM "\n", OHINum);
    if (O2INum < 0) ENZO_VFAIL("O2INum=%" ISYM "\n", O2INum);
    if (CINum < 0) ENZO_VFAIL("CINum=%" ISYM "\n", CINum);
    if (HIINum < 0) ENZO_VFAIL("HIINum=%" ISYM "\n", HIINum);
    if (HCOIINum < 0) ENZO_VFAIL("HCOIINum=%" ISYM "\n", HCOIINum);
    if (H2OINum < 0) ENZO_VFAIL("H2OINum=%" ISYM "\n", H2OINum);
    if (OINum < 0) ENZO_VFAIL("OINum=%" ISYM "\n", OINum);
    if (DeNum < 0) ENZO_VFAIL("DeNum=%" ISYM "\n", DeNum);
    if (COINum < 0) ENZO_VFAIL("COINum=%" ISYM "\n", COINum);
    if (H2INum < 0) ENZO_VFAIL("H2INum=%" ISYM "\n", H2INum);
    if (HINum < 0) ENZO_VFAIL("HINum=%" ISYM "\n", HINum);
    return SUCCESS;
}

int grid::IdentifyNaunetSpeciesFields(int *specnum)
{

    const field_type NauentFields[114] = {
        GH2CNIDensity,
        GHNCIDensity,
        GNO2IDensity,
        GSiOIDensity,
        GCOIDensity,
        GHNCOIDensity,
        GMgIDensity,
        GNOIDensity,
        GO2IDensity,
        GO2HIDensity,
        GSiCIDensity,
        GSiC2IDensity,
        GSiC3IDensity,
        GCH3OHIDensity,
        GCO2IDensity,
        GH2SiOIDensity,
        GHNOIDensity,
        GN2IDensity,
        GH2COIDensity,
        GHCNIDensity,
        GH2OIDensity,
        GNH3IDensity,
        SiC3IIDensity,
        H2CNIDensity,
        GCH4IDensity,
        H2NOIIDensity,
        H2SiOIDensity,
        HeHIIDensity,
        HNCOIDensity,
        HOCIIDensity,
        SiC2IIDensity,
        GSiH4IDensity,
        SiC2IDensity,
        SiC3IDensity,
        SiH5IIDensity,
        SiH4IIDensity,
        SiCIIDensity,
        O2HIDensity,
        SiCIDensity,
        NO2IDensity,
        SiH3IIDensity,
        SiH2IIDensity,
        OCNIDensity,
        SiH2IDensity,
        SiOHIIDensity,
        SiHIIDensity,
        SiH4IDensity,
        SiHIDensity,
        SiH3IDensity,
        SiOIIDensity,
        HCO2IIDensity,
        HNOIDensity,
        CH3OHIDensity,
        MgIDensity,
        MgIIDensity,
        CH4IIDensity,
        SiOIDensity,
        CNIIDensity,
        HCNHIIDensity,
        N2HIIDensity,
        O2HIIDensity,
        SiIIDensity,
        SiIDensity,
        HNCIDensity,
        HNOIIDensity,
        N2IIDensity,
        H3COIIDensity,
        CH4IDensity,
        COIIDensity,
        H2IIDensity,
        NH3IDensity,
        CH3IDensity,
        CO2IDensity,
        NIIDensity,
        OIIDensity,
        HCNIIDensity,
        NH2IIDensity,
        NHIIDensity,
        O2IIDensity,
        CH3IIDensity,
        NH2IDensity,
        CH2IIDensity,
        H2OIIDensity,
        NH3IIDensity,
        NOIIDensity,
        H3OIIDensity,
        N2IDensity,
        CIIDensity,
        HCNIDensity,
        CHIIDensity,
        CH2IDensity,
        H2COIIDensity,
        NHIDensity,
        OHIIDensity,
        CNIDensity,
        H2COIDensity,
        HCOIDensity,
        HeIIDensity,
        CHIDensity,
        H3IIDensity,
        HeIDensity,
        NOIDensity,
        NIDensity,
        OHIDensity,
        O2IDensity,
        CIDensity,
        HIIDensity,
        HCOIIDensity,
        H2OIDensity,
        OIDensity,
        ElectronDensity,
        COIDensity,
        H2IDensity,
        HIDensity
    };

    for (int sidx = 0; sidx < NSPECIES; sidx ++) {
        specnum[sidx] = FindField(NauentFields[sidx], FieldType, NumberOfBaryonFields);
        if (specnum[sidx] < 0) {
            ENZO_VFAIL("specnum[%" ISYM "]=%" ISYM "\n", sidx, specnum[sidx]);
        }
    }

    return SUCCESS;
}


#endif