/***********************************************************************
/
/  GRID CLASS (IDENTIFY THE MULTI-SPECIES FIELDS)
/
/  written by: Chia-Jung Hsu, Patch generated by naunet
/  date:       2021
/
************************************************************************/
// clang-format off
#include "preincludes.h"
#include "macros_and_parameters.h"
#include "typedefs.h"
#include "global_data.h"
#include "Fluxes.h"
#include "GridList.h"
#include "ExternalBoundary.h"
#include "Grid.h"

/* function prototypes */

int FindField(int f, int farray[], int n);

#ifdef USE_NAUNET

int grid::IdentifyNaunetSpeciesFields(int &GCH3OHINum, int &GCH4INum, int
                                      &GCOINum, int &GCO2INum, int &GH2CNINum,
                                      int &GH2COINum, int &GH2OINum, int
                                      &GH2SiOINum, int &GHCNINum, int &GHNCINum,
                                      int &GHNCOINum, int &GHNOINum, int
                                      &GMgINum, int &GN2INum, int &GNH3INum, int
                                      &GNOINum, int &GNO2INum, int &GO2INum, int
                                      &GO2HINum, int &GSiCINum, int &GSiC2INum,
                                      int &GSiC3INum, int &GSiH4INum, int
                                      &GSiOINum, int &CINum, int &CIINum, int
                                      &CHINum, int &CHIINum, int &CH2INum, int
                                      &CH2IINum, int &CH3INum, int &CH3IINum,
                                      int &CH3OHINum, int &CH4INum, int
                                      &CH4IINum, int &CNINum, int &CNIINum, int
                                      &COINum, int &COIINum, int &CO2INum, int
                                      &DeNum, int &HINum, int &HIINum, int
                                      &H2INum, int &H2IINum, int &H2CNINum, int
                                      &H2COINum, int &H2COIINum, int &H2NOIINum,
                                      int &H2OINum, int &H2OIINum, int
                                      &H2SiOINum, int &H3IINum, int &H3COIINum,
                                      int &H3OIINum, int &HCNINum, int
                                      &HCNIINum, int &HCNHIINum, int &HCOINum,
                                      int &HCOIINum, int &HCO2IINum, int
                                      &HeINum, int &HeIINum, int &HeHIINum, int
                                      &HNCINum, int &HNCOINum, int &HNOINum, int
                                      &HNOIINum, int &HOCIINum, int &MgINum, int
                                      &MgIINum, int &NINum, int &NIINum, int
                                      &N2INum, int &N2IINum, int &N2HIINum, int
                                      &NHINum, int &NHIINum, int &NH2INum, int
                                      &NH2IINum, int &NH3INum, int &NH3IINum,
                                      int &NOINum, int &NOIINum, int &NO2INum,
                                      int &OINum, int &OIINum, int &O2INum, int
                                      &O2IINum, int &O2HINum, int &O2HIINum, int
                                      &OCNINum, int &OHINum, int &OHIINum, int
                                      &SiINum, int &SiIINum, int &SiCINum, int
                                      &SiCIINum, int &SiC2INum, int &SiC2IINum,
                                      int &SiC3INum, int &SiC3IINum, int
                                      &SiHINum, int &SiHIINum, int &SiH2INum,
                                      int &SiH2IINum, int &SiH3INum, int
                                      &SiH3IINum, int &SiH4INum, int &SiH4IINum,
                                      int &SiH5IINum, int &SiOINum, int
                                      &SiOIINum, int &SiOHIINum)
{
    GCH3OHINum = GCH4INum = GCOINum = GCO2INum = GH2CNINum = GH2COINum =
    GH2OINum = GH2SiOINum = GHCNINum = GHNCINum = GHNCOINum = GHNOINum = GMgINum
    = GN2INum = GNH3INum = GNOINum = GNO2INum = GO2INum = GO2HINum = GSiCINum =
    GSiC2INum = GSiC3INum = GSiH4INum = GSiOINum = CINum = CIINum = CHINum =
    CHIINum = CH2INum = CH2IINum = CH3INum = CH3IINum = CH3OHINum = CH4INum =
    CH4IINum = CNINum = CNIINum = COINum = COIINum = CO2INum = DeNum = HINum =
    HIINum = H2INum = H2IINum = H2CNINum = H2COINum = H2COIINum = H2NOIINum =
    H2OINum = H2OIINum = H2SiOINum = H3IINum = H3COIINum = H3OIINum = HCNINum =
    HCNIINum = HCNHIINum = HCOINum = HCOIINum = HCO2IINum = HeINum = HeIINum =
    HeHIINum = HNCINum = HNCOINum = HNOINum = HNOIINum = HOCIINum = MgINum =
    MgIINum = NINum = NIINum = N2INum = N2IINum = N2HIINum = NHINum = NHIINum =
    NH2INum = NH2IINum = NH3INum = NH3IINum = NOINum = NOIINum = NO2INum = OINum
    = OIINum = O2INum = O2IINum = O2HINum = O2HIINum = OCNINum = OHINum =
    OHIINum = SiINum = SiIINum = SiCINum = SiCIINum = SiC2INum = SiC2IINum =
    SiC3INum = SiC3IINum = SiHINum = SiHIINum = SiH2INum = SiH2IINum = SiH3INum
    = SiH3IINum = SiH4INum = SiH4IINum = SiH5IINum = SiOINum = SiOIINum =
    SiOHIINum = 0;

    // Find Fields for the Naunet species
    GCH3OHINum = FindField(GCH3OHIDensity, FieldType, NumberOfBaryonFields);
    GCH4INum = FindField(GCH4IDensity, FieldType, NumberOfBaryonFields);
    GCOINum = FindField(GCOIDensity, FieldType, NumberOfBaryonFields);
    GCO2INum = FindField(GCO2IDensity, FieldType, NumberOfBaryonFields);
    GH2CNINum = FindField(GH2CNIDensity, FieldType, NumberOfBaryonFields);
    GH2COINum = FindField(GH2COIDensity, FieldType, NumberOfBaryonFields);
    GH2OINum = FindField(GH2OIDensity, FieldType, NumberOfBaryonFields);
    GH2SiOINum = FindField(GH2SiOIDensity, FieldType, NumberOfBaryonFields);
    GHCNINum = FindField(GHCNIDensity, FieldType, NumberOfBaryonFields);
    GHNCINum = FindField(GHNCIDensity, FieldType, NumberOfBaryonFields);
    GHNCOINum = FindField(GHNCOIDensity, FieldType, NumberOfBaryonFields);
    GHNOINum = FindField(GHNOIDensity, FieldType, NumberOfBaryonFields);
    GMgINum = FindField(GMgIDensity, FieldType, NumberOfBaryonFields);
    GN2INum = FindField(GN2IDensity, FieldType, NumberOfBaryonFields);
    GNH3INum = FindField(GNH3IDensity, FieldType, NumberOfBaryonFields);
    GNOINum = FindField(GNOIDensity, FieldType, NumberOfBaryonFields);
    GNO2INum = FindField(GNO2IDensity, FieldType, NumberOfBaryonFields);
    GO2INum = FindField(GO2IDensity, FieldType, NumberOfBaryonFields);
    GO2HINum = FindField(GO2HIDensity, FieldType, NumberOfBaryonFields);
    GSiCINum = FindField(GSiCIDensity, FieldType, NumberOfBaryonFields);
    GSiC2INum = FindField(GSiC2IDensity, FieldType, NumberOfBaryonFields);
    GSiC3INum = FindField(GSiC3IDensity, FieldType, NumberOfBaryonFields);
    GSiH4INum = FindField(GSiH4IDensity, FieldType, NumberOfBaryonFields);
    GSiOINum = FindField(GSiOIDensity, FieldType, NumberOfBaryonFields);
    CINum = FindField(CIDensity, FieldType, NumberOfBaryonFields);
    CIINum = FindField(CIIDensity, FieldType, NumberOfBaryonFields);
    CHINum = FindField(CHIDensity, FieldType, NumberOfBaryonFields);
    CHIINum = FindField(CHIIDensity, FieldType, NumberOfBaryonFields);
    CH2INum = FindField(CH2IDensity, FieldType, NumberOfBaryonFields);
    CH2IINum = FindField(CH2IIDensity, FieldType, NumberOfBaryonFields);
    CH3INum = FindField(CH3IDensity, FieldType, NumberOfBaryonFields);
    CH3IINum = FindField(CH3IIDensity, FieldType, NumberOfBaryonFields);
    CH3OHINum = FindField(CH3OHIDensity, FieldType, NumberOfBaryonFields);
    CH4INum = FindField(CH4IDensity, FieldType, NumberOfBaryonFields);
    CH4IINum = FindField(CH4IIDensity, FieldType, NumberOfBaryonFields);
    CNINum = FindField(CNIDensity, FieldType, NumberOfBaryonFields);
    CNIINum = FindField(CNIIDensity, FieldType, NumberOfBaryonFields);
    COINum = FindField(COIDensity, FieldType, NumberOfBaryonFields);
    COIINum = FindField(COIIDensity, FieldType, NumberOfBaryonFields);
    CO2INum = FindField(CO2IDensity, FieldType, NumberOfBaryonFields);
    DeNum = FindField(ElectronDensity, FieldType, NumberOfBaryonFields);
    HINum = FindField(HIDensity, FieldType, NumberOfBaryonFields);
    HIINum = FindField(HIIDensity, FieldType, NumberOfBaryonFields);
    H2INum = FindField(H2IDensity, FieldType, NumberOfBaryonFields);
    H2IINum = FindField(H2IIDensity, FieldType, NumberOfBaryonFields);
    H2CNINum = FindField(H2CNIDensity, FieldType, NumberOfBaryonFields);
    H2COINum = FindField(H2COIDensity, FieldType, NumberOfBaryonFields);
    H2COIINum = FindField(H2COIIDensity, FieldType, NumberOfBaryonFields);
    H2NOIINum = FindField(H2NOIIDensity, FieldType, NumberOfBaryonFields);
    H2OINum = FindField(H2OIDensity, FieldType, NumberOfBaryonFields);
    H2OIINum = FindField(H2OIIDensity, FieldType, NumberOfBaryonFields);
    H2SiOINum = FindField(H2SiOIDensity, FieldType, NumberOfBaryonFields);
    H3IINum = FindField(H3IIDensity, FieldType, NumberOfBaryonFields);
    H3COIINum = FindField(H3COIIDensity, FieldType, NumberOfBaryonFields);
    H3OIINum = FindField(H3OIIDensity, FieldType, NumberOfBaryonFields);
    HCNINum = FindField(HCNIDensity, FieldType, NumberOfBaryonFields);
    HCNIINum = FindField(HCNIIDensity, FieldType, NumberOfBaryonFields);
    HCNHIINum = FindField(HCNHIIDensity, FieldType, NumberOfBaryonFields);
    HCOINum = FindField(HCOIDensity, FieldType, NumberOfBaryonFields);
    HCOIINum = FindField(HCOIIDensity, FieldType, NumberOfBaryonFields);
    HCO2IINum = FindField(HCO2IIDensity, FieldType, NumberOfBaryonFields);
    HeINum = FindField(HeIDensity, FieldType, NumberOfBaryonFields);
    HeIINum = FindField(HeIIDensity, FieldType, NumberOfBaryonFields);
    HeHIINum = FindField(HeHIIDensity, FieldType, NumberOfBaryonFields);
    HNCINum = FindField(HNCIDensity, FieldType, NumberOfBaryonFields);
    HNCOINum = FindField(HNCOIDensity, FieldType, NumberOfBaryonFields);
    HNOINum = FindField(HNOIDensity, FieldType, NumberOfBaryonFields);
    HNOIINum = FindField(HNOIIDensity, FieldType, NumberOfBaryonFields);
    HOCIINum = FindField(HOCIIDensity, FieldType, NumberOfBaryonFields);
    MgINum = FindField(MgIDensity, FieldType, NumberOfBaryonFields);
    MgIINum = FindField(MgIIDensity, FieldType, NumberOfBaryonFields);
    NINum = FindField(NIDensity, FieldType, NumberOfBaryonFields);
    NIINum = FindField(NIIDensity, FieldType, NumberOfBaryonFields);
    N2INum = FindField(N2IDensity, FieldType, NumberOfBaryonFields);
    N2IINum = FindField(N2IIDensity, FieldType, NumberOfBaryonFields);
    N2HIINum = FindField(N2HIIDensity, FieldType, NumberOfBaryonFields);
    NHINum = FindField(NHIDensity, FieldType, NumberOfBaryonFields);
    NHIINum = FindField(NHIIDensity, FieldType, NumberOfBaryonFields);
    NH2INum = FindField(NH2IDensity, FieldType, NumberOfBaryonFields);
    NH2IINum = FindField(NH2IIDensity, FieldType, NumberOfBaryonFields);
    NH3INum = FindField(NH3IDensity, FieldType, NumberOfBaryonFields);
    NH3IINum = FindField(NH3IIDensity, FieldType, NumberOfBaryonFields);
    NOINum = FindField(NOIDensity, FieldType, NumberOfBaryonFields);
    NOIINum = FindField(NOIIDensity, FieldType, NumberOfBaryonFields);
    NO2INum = FindField(NO2IDensity, FieldType, NumberOfBaryonFields);
    OINum = FindField(OIDensity, FieldType, NumberOfBaryonFields);
    OIINum = FindField(OIIDensity, FieldType, NumberOfBaryonFields);
    O2INum = FindField(O2IDensity, FieldType, NumberOfBaryonFields);
    O2IINum = FindField(O2IIDensity, FieldType, NumberOfBaryonFields);
    O2HINum = FindField(O2HIDensity, FieldType, NumberOfBaryonFields);
    O2HIINum = FindField(O2HIIDensity, FieldType, NumberOfBaryonFields);
    OCNINum = FindField(OCNIDensity, FieldType, NumberOfBaryonFields);
    OHINum = FindField(OHIDensity, FieldType, NumberOfBaryonFields);
    OHIINum = FindField(OHIIDensity, FieldType, NumberOfBaryonFields);
    SiINum = FindField(SiIDensity, FieldType, NumberOfBaryonFields);
    SiIINum = FindField(SiIIDensity, FieldType, NumberOfBaryonFields);
    SiCINum = FindField(SiCIDensity, FieldType, NumberOfBaryonFields);
    SiCIINum = FindField(SiCIIDensity, FieldType, NumberOfBaryonFields);
    SiC2INum = FindField(SiC2IDensity, FieldType, NumberOfBaryonFields);
    SiC2IINum = FindField(SiC2IIDensity, FieldType, NumberOfBaryonFields);
    SiC3INum = FindField(SiC3IDensity, FieldType, NumberOfBaryonFields);
    SiC3IINum = FindField(SiC3IIDensity, FieldType, NumberOfBaryonFields);
    SiHINum = FindField(SiHIDensity, FieldType, NumberOfBaryonFields);
    SiHIINum = FindField(SiHIIDensity, FieldType, NumberOfBaryonFields);
    SiH2INum = FindField(SiH2IDensity, FieldType, NumberOfBaryonFields);
    SiH2IINum = FindField(SiH2IIDensity, FieldType, NumberOfBaryonFields);
    SiH3INum = FindField(SiH3IDensity, FieldType, NumberOfBaryonFields);
    SiH3IINum = FindField(SiH3IIDensity, FieldType, NumberOfBaryonFields);
    SiH4INum = FindField(SiH4IDensity, FieldType, NumberOfBaryonFields);
    SiH4IINum = FindField(SiH4IIDensity, FieldType, NumberOfBaryonFields);
    SiH5IINum = FindField(SiH5IIDensity, FieldType, NumberOfBaryonFields);
    SiOINum = FindField(SiOIDensity, FieldType, NumberOfBaryonFields);
    SiOIINum = FindField(SiOIIDensity, FieldType, NumberOfBaryonFields);
    SiOHIINum = FindField(SiOHIIDensity, FieldType, NumberOfBaryonFields);
    // check fields exist
    if (GCH3OHINum < 0) ENZO_VFAIL("GCH3OHINum=%" ISYM "\n", GCH3OHINum);
    if (GCH4INum < 0) ENZO_VFAIL("GCH4INum=%" ISYM "\n", GCH4INum);
    if (GCOINum < 0) ENZO_VFAIL("GCOINum=%" ISYM "\n", GCOINum);
    if (GCO2INum < 0) ENZO_VFAIL("GCO2INum=%" ISYM "\n", GCO2INum);
    if (GH2CNINum < 0) ENZO_VFAIL("GH2CNINum=%" ISYM "\n", GH2CNINum);
    if (GH2COINum < 0) ENZO_VFAIL("GH2COINum=%" ISYM "\n", GH2COINum);
    if (GH2OINum < 0) ENZO_VFAIL("GH2OINum=%" ISYM "\n", GH2OINum);
    if (GH2SiOINum < 0) ENZO_VFAIL("GH2SiOINum=%" ISYM "\n", GH2SiOINum);
    if (GHCNINum < 0) ENZO_VFAIL("GHCNINum=%" ISYM "\n", GHCNINum);
    if (GHNCINum < 0) ENZO_VFAIL("GHNCINum=%" ISYM "\n", GHNCINum);
    if (GHNCOINum < 0) ENZO_VFAIL("GHNCOINum=%" ISYM "\n", GHNCOINum);
    if (GHNOINum < 0) ENZO_VFAIL("GHNOINum=%" ISYM "\n", GHNOINum);
    if (GMgINum < 0) ENZO_VFAIL("GMgINum=%" ISYM "\n", GMgINum);
    if (GN2INum < 0) ENZO_VFAIL("GN2INum=%" ISYM "\n", GN2INum);
    if (GNH3INum < 0) ENZO_VFAIL("GNH3INum=%" ISYM "\n", GNH3INum);
    if (GNOINum < 0) ENZO_VFAIL("GNOINum=%" ISYM "\n", GNOINum);
    if (GNO2INum < 0) ENZO_VFAIL("GNO2INum=%" ISYM "\n", GNO2INum);
    if (GO2INum < 0) ENZO_VFAIL("GO2INum=%" ISYM "\n", GO2INum);
    if (GO2HINum < 0) ENZO_VFAIL("GO2HINum=%" ISYM "\n", GO2HINum);
    if (GSiCINum < 0) ENZO_VFAIL("GSiCINum=%" ISYM "\n", GSiCINum);
    if (GSiC2INum < 0) ENZO_VFAIL("GSiC2INum=%" ISYM "\n", GSiC2INum);
    if (GSiC3INum < 0) ENZO_VFAIL("GSiC3INum=%" ISYM "\n", GSiC3INum);
    if (GSiH4INum < 0) ENZO_VFAIL("GSiH4INum=%" ISYM "\n", GSiH4INum);
    if (GSiOINum < 0) ENZO_VFAIL("GSiOINum=%" ISYM "\n", GSiOINum);
    if (CINum < 0) ENZO_VFAIL("CINum=%" ISYM "\n", CINum);
    if (CIINum < 0) ENZO_VFAIL("CIINum=%" ISYM "\n", CIINum);
    if (CHINum < 0) ENZO_VFAIL("CHINum=%" ISYM "\n", CHINum);
    if (CHIINum < 0) ENZO_VFAIL("CHIINum=%" ISYM "\n", CHIINum);
    if (CH2INum < 0) ENZO_VFAIL("CH2INum=%" ISYM "\n", CH2INum);
    if (CH2IINum < 0) ENZO_VFAIL("CH2IINum=%" ISYM "\n", CH2IINum);
    if (CH3INum < 0) ENZO_VFAIL("CH3INum=%" ISYM "\n", CH3INum);
    if (CH3IINum < 0) ENZO_VFAIL("CH3IINum=%" ISYM "\n", CH3IINum);
    if (CH3OHINum < 0) ENZO_VFAIL("CH3OHINum=%" ISYM "\n", CH3OHINum);
    if (CH4INum < 0) ENZO_VFAIL("CH4INum=%" ISYM "\n", CH4INum);
    if (CH4IINum < 0) ENZO_VFAIL("CH4IINum=%" ISYM "\n", CH4IINum);
    if (CNINum < 0) ENZO_VFAIL("CNINum=%" ISYM "\n", CNINum);
    if (CNIINum < 0) ENZO_VFAIL("CNIINum=%" ISYM "\n", CNIINum);
    if (COINum < 0) ENZO_VFAIL("COINum=%" ISYM "\n", COINum);
    if (COIINum < 0) ENZO_VFAIL("COIINum=%" ISYM "\n", COIINum);
    if (CO2INum < 0) ENZO_VFAIL("CO2INum=%" ISYM "\n", CO2INum);
    if (DeNum < 0) ENZO_VFAIL("DeNum=%" ISYM "\n", DeNum);
    if (HINum < 0) ENZO_VFAIL("HINum=%" ISYM "\n", HINum);
    if (HIINum < 0) ENZO_VFAIL("HIINum=%" ISYM "\n", HIINum);
    if (H2INum < 0) ENZO_VFAIL("H2INum=%" ISYM "\n", H2INum);
    if (H2IINum < 0) ENZO_VFAIL("H2IINum=%" ISYM "\n", H2IINum);
    if (H2CNINum < 0) ENZO_VFAIL("H2CNINum=%" ISYM "\n", H2CNINum);
    if (H2COINum < 0) ENZO_VFAIL("H2COINum=%" ISYM "\n", H2COINum);
    if (H2COIINum < 0) ENZO_VFAIL("H2COIINum=%" ISYM "\n", H2COIINum);
    if (H2NOIINum < 0) ENZO_VFAIL("H2NOIINum=%" ISYM "\n", H2NOIINum);
    if (H2OINum < 0) ENZO_VFAIL("H2OINum=%" ISYM "\n", H2OINum);
    if (H2OIINum < 0) ENZO_VFAIL("H2OIINum=%" ISYM "\n", H2OIINum);
    if (H2SiOINum < 0) ENZO_VFAIL("H2SiOINum=%" ISYM "\n", H2SiOINum);
    if (H3IINum < 0) ENZO_VFAIL("H3IINum=%" ISYM "\n", H3IINum);
    if (H3COIINum < 0) ENZO_VFAIL("H3COIINum=%" ISYM "\n", H3COIINum);
    if (H3OIINum < 0) ENZO_VFAIL("H3OIINum=%" ISYM "\n", H3OIINum);
    if (HCNINum < 0) ENZO_VFAIL("HCNINum=%" ISYM "\n", HCNINum);
    if (HCNIINum < 0) ENZO_VFAIL("HCNIINum=%" ISYM "\n", HCNIINum);
    if (HCNHIINum < 0) ENZO_VFAIL("HCNHIINum=%" ISYM "\n", HCNHIINum);
    if (HCOINum < 0) ENZO_VFAIL("HCOINum=%" ISYM "\n", HCOINum);
    if (HCOIINum < 0) ENZO_VFAIL("HCOIINum=%" ISYM "\n", HCOIINum);
    if (HCO2IINum < 0) ENZO_VFAIL("HCO2IINum=%" ISYM "\n", HCO2IINum);
    if (HeINum < 0) ENZO_VFAIL("HeINum=%" ISYM "\n", HeINum);
    if (HeIINum < 0) ENZO_VFAIL("HeIINum=%" ISYM "\n", HeIINum);
    if (HeHIINum < 0) ENZO_VFAIL("HeHIINum=%" ISYM "\n", HeHIINum);
    if (HNCINum < 0) ENZO_VFAIL("HNCINum=%" ISYM "\n", HNCINum);
    if (HNCOINum < 0) ENZO_VFAIL("HNCOINum=%" ISYM "\n", HNCOINum);
    if (HNOINum < 0) ENZO_VFAIL("HNOINum=%" ISYM "\n", HNOINum);
    if (HNOIINum < 0) ENZO_VFAIL("HNOIINum=%" ISYM "\n", HNOIINum);
    if (HOCIINum < 0) ENZO_VFAIL("HOCIINum=%" ISYM "\n", HOCIINum);
    if (MgINum < 0) ENZO_VFAIL("MgINum=%" ISYM "\n", MgINum);
    if (MgIINum < 0) ENZO_VFAIL("MgIINum=%" ISYM "\n", MgIINum);
    if (NINum < 0) ENZO_VFAIL("NINum=%" ISYM "\n", NINum);
    if (NIINum < 0) ENZO_VFAIL("NIINum=%" ISYM "\n", NIINum);
    if (N2INum < 0) ENZO_VFAIL("N2INum=%" ISYM "\n", N2INum);
    if (N2IINum < 0) ENZO_VFAIL("N2IINum=%" ISYM "\n", N2IINum);
    if (N2HIINum < 0) ENZO_VFAIL("N2HIINum=%" ISYM "\n", N2HIINum);
    if (NHINum < 0) ENZO_VFAIL("NHINum=%" ISYM "\n", NHINum);
    if (NHIINum < 0) ENZO_VFAIL("NHIINum=%" ISYM "\n", NHIINum);
    if (NH2INum < 0) ENZO_VFAIL("NH2INum=%" ISYM "\n", NH2INum);
    if (NH2IINum < 0) ENZO_VFAIL("NH2IINum=%" ISYM "\n", NH2IINum);
    if (NH3INum < 0) ENZO_VFAIL("NH3INum=%" ISYM "\n", NH3INum);
    if (NH3IINum < 0) ENZO_VFAIL("NH3IINum=%" ISYM "\n", NH3IINum);
    if (NOINum < 0) ENZO_VFAIL("NOINum=%" ISYM "\n", NOINum);
    if (NOIINum < 0) ENZO_VFAIL("NOIINum=%" ISYM "\n", NOIINum);
    if (NO2INum < 0) ENZO_VFAIL("NO2INum=%" ISYM "\n", NO2INum);
    if (OINum < 0) ENZO_VFAIL("OINum=%" ISYM "\n", OINum);
    if (OIINum < 0) ENZO_VFAIL("OIINum=%" ISYM "\n", OIINum);
    if (O2INum < 0) ENZO_VFAIL("O2INum=%" ISYM "\n", O2INum);
    if (O2IINum < 0) ENZO_VFAIL("O2IINum=%" ISYM "\n", O2IINum);
    if (O2HINum < 0) ENZO_VFAIL("O2HINum=%" ISYM "\n", O2HINum);
    if (O2HIINum < 0) ENZO_VFAIL("O2HIINum=%" ISYM "\n", O2HIINum);
    if (OCNINum < 0) ENZO_VFAIL("OCNINum=%" ISYM "\n", OCNINum);
    if (OHINum < 0) ENZO_VFAIL("OHINum=%" ISYM "\n", OHINum);
    if (OHIINum < 0) ENZO_VFAIL("OHIINum=%" ISYM "\n", OHIINum);
    if (SiINum < 0) ENZO_VFAIL("SiINum=%" ISYM "\n", SiINum);
    if (SiIINum < 0) ENZO_VFAIL("SiIINum=%" ISYM "\n", SiIINum);
    if (SiCINum < 0) ENZO_VFAIL("SiCINum=%" ISYM "\n", SiCINum);
    if (SiCIINum < 0) ENZO_VFAIL("SiCIINum=%" ISYM "\n", SiCIINum);
    if (SiC2INum < 0) ENZO_VFAIL("SiC2INum=%" ISYM "\n", SiC2INum);
    if (SiC2IINum < 0) ENZO_VFAIL("SiC2IINum=%" ISYM "\n", SiC2IINum);
    if (SiC3INum < 0) ENZO_VFAIL("SiC3INum=%" ISYM "\n", SiC3INum);
    if (SiC3IINum < 0) ENZO_VFAIL("SiC3IINum=%" ISYM "\n", SiC3IINum);
    if (SiHINum < 0) ENZO_VFAIL("SiHINum=%" ISYM "\n", SiHINum);
    if (SiHIINum < 0) ENZO_VFAIL("SiHIINum=%" ISYM "\n", SiHIINum);
    if (SiH2INum < 0) ENZO_VFAIL("SiH2INum=%" ISYM "\n", SiH2INum);
    if (SiH2IINum < 0) ENZO_VFAIL("SiH2IINum=%" ISYM "\n", SiH2IINum);
    if (SiH3INum < 0) ENZO_VFAIL("SiH3INum=%" ISYM "\n", SiH3INum);
    if (SiH3IINum < 0) ENZO_VFAIL("SiH3IINum=%" ISYM "\n", SiH3IINum);
    if (SiH4INum < 0) ENZO_VFAIL("SiH4INum=%" ISYM "\n", SiH4INum);
    if (SiH4IINum < 0) ENZO_VFAIL("SiH4IINum=%" ISYM "\n", SiH4IINum);
    if (SiH5IINum < 0) ENZO_VFAIL("SiH5IINum=%" ISYM "\n", SiH5IINum);
    if (SiOINum < 0) ENZO_VFAIL("SiOINum=%" ISYM "\n", SiOINum);
    if (SiOIINum < 0) ENZO_VFAIL("SiOIINum=%" ISYM "\n", SiOIINum);
    if (SiOHIINum < 0) ENZO_VFAIL("SiOHIINum=%" ISYM "\n", SiOHIINum);
    return SUCCESS;
}

#endif