NELEM = 7
NSPEC = 114
NGAS = 90
NICE = 24
NGRAIN = 0
NREAC = 1403
HAS_THERMAL = False

ALL_ELEMENTS = [
    "Mg",
    "Si",
    "He",
    "N",
    "C",
    "O",
    "H",
]

ALL_SPECIES = [
    "#H2CN",
    "#HNC",
    "#NO2",
    "#SiO",
    "#CO",
    "#HNCO",
    "#Mg",
    "#NO",
    "#O2",
    "#O2H",
    "#SiC",
    "#SiC2",
    "#SiC3",
    "#CH3OH",
    "#CO2",
    "#H2SiO",
    "#HNO",
    "#N2",
    "#H2CO",
    "#HCN",
    "#H2O",
    "#NH3",
    "SiC3+",
    "H2CN",
    "#CH4",
    "H2NO+",
    "H2SiO",
    "HNCO",
    "HOC+",
    "HeH+",
    "SiC2+",
    "#SiH4",
    "SiC2",
    "SiC3",
    "SiH5+",
    "SiH4+",
    "SiC+",
    "O2H",
    "SiC",
    "NO2",
    "SiH3+",
    "SiH2+",
    "OCN",
    "SiH2",
    "SiOH+",
    "SiH+",
    "SiH4",
    "SiH",
    "SiH3",
    "SiO+",
    "HCO2+",
    "HNO",
    "CH3OH",
    "Mg",
    "Mg+",
    "CH4+",
    "SiO",
    "CN+",
    "HCNH+",
    "N2H+",
    "O2H+",
    "Si+",
    "Si",
    "HNC",
    "HNO+",
    "N2+",
    "H3CO+",
    "CH4",
    "CO+",
    "H2+",
    "NH3",
    "CH3",
    "CO2",
    "N+",
    "O+",
    "HCN+",
    "NH2+",
    "NH+",
    "O2+",
    "CH3+",
    "NH2",
    "CH2+",
    "H2O+",
    "NH3+",
    "NO+",
    "H3O+",
    "N2",
    "C+",
    "HCN",
    "CH+",
    "CH2",
    "H2CO+",
    "NH",
    "OH+",
    "CN",
    "H2CO",
    "HCO",
    "He+",
    "CH",
    "H3+",
    "He",
    "NO",
    "N",
    "OH",
    "O2",
    "C",
    "H+",
    "HCO+",
    "H2O",
    "O",
    "e-",
    "CO",
    "H2",
    "H",
]

ALL_ALIAS = [
    "GH2CNI",
    "GHNCI",
    "GNO2I",
    "GSiOI",
    "GCOI",
    "GHNCOI",
    "GMgI",
    "GNOI",
    "GO2I",
    "GO2HI",
    "GSiCI",
    "GSiC2I",
    "GSiC3I",
    "GCH3OHI",
    "GCO2I",
    "GH2SiOI",
    "GHNOI",
    "GN2I",
    "GH2COI",
    "GHCNI",
    "GH2OI",
    "GNH3I",
    "SiC3II",
    "H2CNI",
    "GCH4I",
    "H2NOII",
    "H2SiOI",
    "HNCOI",
    "HOCII",
    "HeHII",
    "SiC2II",
    "GSiH4I",
    "SiC2I",
    "SiC3I",
    "SiH5II",
    "SiH4II",
    "SiCII",
    "O2HI",
    "SiCI",
    "NO2I",
    "SiH3II",
    "SiH2II",
    "OCNI",
    "SiH2I",
    "SiOHII",
    "SiHII",
    "SiH4I",
    "SiHI",
    "SiH3I",
    "SiOII",
    "HCO2II",
    "HNOI",
    "CH3OHI",
    "MgI",
    "MgII",
    "CH4II",
    "SiOI",
    "CNII",
    "HCNHII",
    "N2HII",
    "O2HII",
    "SiII",
    "SiI",
    "HNCI",
    "HNOII",
    "N2II",
    "H3COII",
    "CH4I",
    "COII",
    "H2II",
    "NH3I",
    "CH3I",
    "CO2I",
    "NII",
    "OII",
    "HCNII",
    "NH2II",
    "NHII",
    "O2II",
    "CH3II",
    "NH2I",
    "CH2II",
    "H2OII",
    "NH3II",
    "NOII",
    "H3OII",
    "N2I",
    "CII",
    "HCNI",
    "CHII",
    "CH2I",
    "H2COII",
    "NHI",
    "OHII",
    "CNI",
    "H2COI",
    "HCOI",
    "HeII",
    "CHI",
    "H3II",
    "HeI",
    "NOI",
    "NI",
    "OHI",
    "O2I",
    "CI",
    "HII",
    "HCOII",
    "H2OI",
    "OI",
    "eM",
    "COI",
    "H2I",
    "HI",
]

ALL_GAS_SPECIES = [
    "SiC3+",
    "H2CN",
    "H2NO+",
    "H2SiO",
    "HNCO",
    "HOC+",
    "HeH+",
    "SiC2+",
    "SiC2",
    "SiC3",
    "SiH5+",
    "SiH4+",
    "SiC+",
    "O2H",
    "SiC",
    "NO2",
    "SiH3+",
    "SiH2+",
    "OCN",
    "SiH2",
    "SiOH+",
    "SiH+",
    "SiH4",
    "SiH",
    "SiH3",
    "SiO+",
    "HCO2+",
    "HNO",
    "CH3OH",
    "Mg",
    "Mg+",
    "CH4+",
    "SiO",
    "CN+",
    "HCNH+",
    "N2H+",
    "O2H+",
    "Si+",
    "Si",
    "HNC",
    "HNO+",
    "N2+",
    "H3CO+",
    "CH4",
    "CO+",
    "H2+",
    "NH3",
    "CH3",
    "CO2",
    "N+",
    "O+",
    "HCN+",
    "NH2+",
    "NH+",
    "O2+",
    "CH3+",
    "NH2",
    "CH2+",
    "H2O+",
    "NH3+",
    "NO+",
    "H3O+",
    "N2",
    "C+",
    "HCN",
    "CH+",
    "CH2",
    "H2CO+",
    "NH",
    "OH+",
    "CN",
    "H2CO",
    "HCO",
    "He+",
    "CH",
    "H3+",
    "He",
    "NO",
    "N",
    "OH",
    "O2",
    "C",
    "H+",
    "HCO+",
    "H2O",
    "O",
    "e-",
    "CO",
    "H2",
    "H",
]

ALL_ICE_SPECIES = [
    "#H2CN",
    "#HNC",
    "#NO2",
    "#SiO",
    "#CO",
    "#HNCO",
    "#Mg",
    "#NO",
    "#O2",
    "#O2H",
    "#SiC",
    "#SiC2",
    "#SiC3",
    "#CH3OH",
    "#CO2",
    "#H2SiO",
    "#HNO",
    "#N2",
    "#H2CO",
    "#HCN",
    "#H2O",
    "#NH3",
    "#CH4",
    "#SiH4",
]

ALL_GRAIN_SPECIES = [
]

# species grouped by elements and the corresponding element count
TABLE_SPECIES_GROUPED_BY_ELEMENTS = {
    "Mg": {
        "#Mg": 1,
        "Mg": 1,
        "Mg+": 1,
    },
    "Si": {
        "#SiO": 1,
        "#SiC": 1,
        "#SiC2": 1,
        "#SiC3": 1,
        "#H2SiO": 1,
        "SiC3+": 1,
        "H2SiO": 1,
        "SiC2+": 1,
        "#SiH4": 1,
        "SiC2": 1,
        "SiC3": 1,
        "SiH5+": 1,
        "SiH4+": 1,
        "SiC+": 1,
        "SiC": 1,
        "SiH3+": 1,
        "SiH2+": 1,
        "SiH2": 1,
        "SiOH+": 1,
        "SiH+": 1,
        "SiH4": 1,
        "SiH": 1,
        "SiH3": 1,
        "SiO+": 1,
        "SiO": 1,
        "Si+": 1,
        "Si": 1,
    },
    "He": {
        "HeH+": 1,
        "He+": 1,
        "He": 1,
    },
    "N": {
        "#H2CN": 1,
        "#HNC": 1,
        "#NO2": 1,
        "#HNCO": 1,
        "#NO": 1,
        "#HNO": 1,
        "#N2": 2,
        "#HCN": 1,
        "#NH3": 1,
        "H2CN": 1,
        "H2NO+": 1,
        "HNCO": 1,
        "NO2": 1,
        "OCN": 1,
        "HNO": 1,
        "CN+": 1,
        "HCNH+": 1,
        "N2H+": 2,
        "HNC": 1,
        "HNO+": 1,
        "N2+": 2,
        "NH3": 1,
        "N+": 1,
        "HCN+": 1,
        "NH2+": 1,
        "NH+": 1,
        "NH2": 1,
        "NH3+": 1,
        "NO+": 1,
        "N2": 2,
        "HCN": 1,
        "NH": 1,
        "CN": 1,
        "NO": 1,
        "N": 1,
    },
    "C": {
        "#H2CN": 1,
        "#HNC": 1,
        "#CO": 1,
        "#HNCO": 1,
        "#SiC": 1,
        "#SiC2": 2,
        "#SiC3": 3,
        "#CH3OH": 1,
        "#CO2": 1,
        "#H2CO": 1,
        "#HCN": 1,
        "SiC3+": 3,
        "H2CN": 1,
        "#CH4": 1,
        "HNCO": 1,
        "HOC+": 1,
        "SiC2+": 2,
        "SiC2": 2,
        "SiC3": 3,
        "SiC+": 1,
        "SiC": 1,
        "OCN": 1,
        "HCO2+": 1,
        "CH3OH": 1,
        "CH4+": 1,
        "CN+": 1,
        "HCNH+": 1,
        "HNC": 1,
        "H3CO+": 1,
        "CH4": 1,
        "CO+": 1,
        "CH3": 1,
        "CO2": 1,
        "HCN+": 1,
        "CH3+": 1,
        "CH2+": 1,
        "C+": 1,
        "HCN": 1,
        "CH+": 1,
        "CH2": 1,
        "H2CO+": 1,
        "CN": 1,
        "H2CO": 1,
        "HCO": 1,
        "CH": 1,
        "C": 1,
        "HCO+": 1,
        "CO": 1,
    },
    "O": {
        "#NO2": 2,
        "#SiO": 1,
        "#CO": 1,
        "#HNCO": 1,
        "#NO": 1,
        "#O2": 2,
        "#O2H": 2,
        "#CH3OH": 1,
        "#CO2": 2,
        "#H2SiO": 1,
        "#HNO": 1,
        "#H2CO": 1,
        "#H2O": 1,
        "H2NO+": 1,
        "H2SiO": 1,
        "HNCO": 1,
        "HOC+": 1,
        "O2H": 2,
        "NO2": 2,
        "OCN": 1,
        "SiOH+": 1,
        "SiO+": 1,
        "HCO2+": 2,
        "HNO": 1,
        "CH3OH": 1,
        "SiO": 1,
        "O2H+": 2,
        "HNO+": 1,
        "H3CO+": 1,
        "CO+": 1,
        "CO2": 2,
        "O+": 1,
        "O2+": 2,
        "H2O+": 1,
        "NO+": 1,
        "H3O+": 1,
        "H2CO+": 1,
        "OH+": 1,
        "H2CO": 1,
        "HCO": 1,
        "NO": 1,
        "OH": 1,
        "O2": 2,
        "HCO+": 1,
        "H2O": 1,
        "O": 1,
        "CO": 1,
    },
    "H": {
        "#H2CN": 2,
        "#HNC": 1,
        "#HNCO": 1,
        "#O2H": 1,
        "#CH3OH": 4,
        "#H2SiO": 2,
        "#HNO": 1,
        "#H2CO": 2,
        "#HCN": 1,
        "#H2O": 2,
        "#NH3": 3,
        "H2CN": 2,
        "#CH4": 4,
        "H2NO+": 2,
        "H2SiO": 2,
        "HNCO": 1,
        "HOC+": 1,
        "HeH+": 1,
        "#SiH4": 4,
        "SiH5+": 5,
        "SiH4+": 4,
        "O2H": 1,
        "SiH3+": 3,
        "SiH2+": 2,
        "SiH2": 2,
        "SiOH+": 1,
        "SiH+": 1,
        "SiH4": 4,
        "SiH": 1,
        "SiH3": 3,
        "HCO2+": 1,
        "HNO": 1,
        "CH3OH": 4,
        "CH4+": 4,
        "HCNH+": 2,
        "N2H+": 1,
        "O2H+": 1,
        "HNC": 1,
        "HNO+": 1,
        "H3CO+": 3,
        "CH4": 4,
        "H2+": 2,
        "NH3": 3,
        "CH3": 3,
        "HCN+": 1,
        "NH2+": 2,
        "NH+": 1,
        "CH3+": 3,
        "NH2": 2,
        "CH2+": 2,
        "H2O+": 2,
        "NH3+": 3,
        "H3O+": 3,
        "HCN": 1,
        "CH+": 1,
        "CH2": 2,
        "H2CO+": 2,
        "NH": 1,
        "OH+": 1,
        "H2CO": 2,
        "HCO": 1,
        "CH": 1,
        "H3+": 3,
        "OH": 1,
        "H+": 1,
        "HCO+": 1,
        "H2O": 2,
        "H2": 2,
        "H": 1,
    },
}
